// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"
)

// Attachment corresponds to model "widgets.attachment".
type Attachment struct {
	ID            string     `db:"id"`
	TenantID      string     `db:"tenant_id"`
	CreatedAt     time.Time  `db:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at"`
	DeletedAt     *time.Time `db:"deleted_at"`
	CreatedBy     *string    `db:"created_by"`
	Etag          string     `db:"etag"`
	ReferenceType string     `db:"reference_type"`
	ReferenceID   string     `db:"reference_id"`
}
