// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Attachment corresponds to model "widgets.attachment".
type Attachment struct {
	ID            string     `db:"id"`
	TenantID      string     `db:"tenant_id"`
	CreatedAt     time.Time  `db:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at"`
	DeletedAt     *time.Time `db:"deleted_at"`
	CreatedBy     *string    `db:"created_by"`
	Etag          string     `db:"etag"`
	ReferenceType string     `db:"reference_type"`
	ReferenceID   string     `db:"reference_id"`
}

func (Attachment) ResourceName() string { return "widgets.attachment" }

// AttachmentFields is one orm field descriptor per Condition-bearing column.
var AttachmentFields = struct {
	ID            orm.Field[Attachment, string]
	TenantID      orm.Field[Attachment, string]
	CreatedAt     orm.TimeField[Attachment]
	UpdatedAt     orm.TimeField[Attachment]
	DeletedAt     orm.TimeField[Attachment]
	CreatedBy     orm.Field[Attachment, string]
	Etag          orm.StringField[Attachment]
	ReferenceType orm.Field[Attachment, string]
	ReferenceID   orm.Field[Attachment, string]
}{
	ID:            orm.NewField[Attachment, string]("id"),
	TenantID:      orm.NewField[Attachment, string]("tenant_id"),
	CreatedAt:     orm.NewTimeField[Attachment]("created_at"),
	UpdatedAt:     orm.NewTimeField[Attachment]("updated_at"),
	DeletedAt:     orm.NewTimeField[Attachment]("deleted_at"),
	CreatedBy:     orm.NewField[Attachment, string]("created_by"),
	Etag:          orm.NewStringField[Attachment]("etag"),
	ReferenceType: orm.NewField[Attachment, string]("reference_type"),
	ReferenceID:   orm.NewField[Attachment, string]("reference_id"),
}

// AttachmentAllFields is Query[Attachment]'s default Select() list.
var AttachmentAllFields = []orm.AnyField[Attachment]{
	AttachmentFields.ID,
	AttachmentFields.TenantID,
	AttachmentFields.CreatedAt,
	AttachmentFields.UpdatedAt,
	AttachmentFields.DeletedAt,
	AttachmentFields.CreatedBy,
	AttachmentFields.Etag,
	AttachmentFields.ReferenceType,
	AttachmentFields.ReferenceID,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Attachment) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Attachment", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Attachment", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Attachment", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["reference_type"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "ReferenceType", "string", v)
		}
		x.ReferenceType = val
	}
	if v, ok := row["reference_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Attachment", "ReferenceID", "string", v)
		}
		x.ReferenceID = val
	}
	return nil
}

// AttachmentValues is a typed builder for Attachment's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type AttachmentValues struct {
	orm.Values[Attachment]
}

func NewAttachmentValues() *AttachmentValues {
	return &AttachmentValues{Values: *orm.NewValues[Attachment]()}
}

func (v *AttachmentValues) SetID(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.ID, x)
	return v
}

func (v *AttachmentValues) SetTenantID(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.TenantID, x)
	return v
}

func (v *AttachmentValues) SetCreatedAt(x time.Time) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.CreatedAt.Field, x)
	return v
}

func (v *AttachmentValues) SetUpdatedAt(x time.Time) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.UpdatedAt.Field, x)
	return v
}

func (v *AttachmentValues) SetDeletedAt(x time.Time) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.DeletedAt.Field, x)
	return v
}

func (v *AttachmentValues) SetCreatedBy(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.CreatedBy, x)
	return v
}

func (v *AttachmentValues) SetEtag(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.Etag.Field, x)
	return v
}

func (v *AttachmentValues) SetReferenceType(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.ReferenceType, x)
	return v
}

func (v *AttachmentValues) SetReferenceID(x string) *AttachmentValues {
	orm.Set(&v.Values, AttachmentFields.ReferenceID, x)
	return v
}
