// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Card corresponds to model "widgets.card".
type Card struct {
	ID        string     `db:"id"`
	TenantID  string     `db:"tenant_id"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
	CreatedBy *string    `db:"created_by"`
	Etag      string     `db:"etag"`
	Name      string     `db:"name"`
	Phone     *string    `db:"phone"`
}

func (Card) ResourceName() string { return "widgets.card" }

// CardFields is one orm field descriptor per Condition-bearing column.
var CardFields = struct {
	ID        orm.Field[Card, string]
	TenantID  orm.Field[Card, string]
	CreatedAt orm.TimeField[Card]
	UpdatedAt orm.TimeField[Card]
	DeletedAt orm.TimeField[Card]
	CreatedBy orm.Field[Card, string]
	Etag      orm.StringField[Card]
	Name      orm.StringField[Card]
	Phone     orm.StringField[Card]
}{
	ID:        orm.NewField[Card, string]("id"),
	TenantID:  orm.NewField[Card, string]("tenant_id"),
	CreatedAt: orm.NewTimeField[Card]("created_at"),
	UpdatedAt: orm.NewTimeField[Card]("updated_at"),
	DeletedAt: orm.NewTimeField[Card]("deleted_at"),
	CreatedBy: orm.NewField[Card, string]("created_by"),
	Etag:      orm.NewStringField[Card]("etag"),
	Name:      orm.NewStringField[Card]("name"),
	Phone:     orm.NewStringField[Card]("phone"),
}

// CardAllFields is Query[Card]'s default Select() list.
var CardAllFields = []orm.AnyField[Card]{
	CardFields.ID,
	CardFields.TenantID,
	CardFields.CreatedAt,
	CardFields.UpdatedAt,
	CardFields.DeletedAt,
	CardFields.CreatedBy,
	CardFields.Etag,
	CardFields.Name,
	CardFields.Phone,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Card) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Card", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Card", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Card", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["name"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "Name", "string", v)
		}
		x.Name = val
	}
	if v, ok := row["phone"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Card", "Phone", "*string", v)
		}
		x.Phone = &val
	}
	return nil
}

// CardValues is a typed builder for Card's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type CardValues struct {
	orm.Values[Card]
}

func NewCardValues() *CardValues {
	return &CardValues{Values: *orm.NewValues[Card]()}
}

func (v *CardValues) SetName(x string) *CardValues {
	orm.Set(&v.Values, CardFields.Name.Field, x)
	return v
}

func (v *CardValues) SetPhone(x string) *CardValues {
	orm.Set(&v.Values, CardFields.Phone.Field, x)
	return v
}

// Query returns a fresh Card query — sugar over orm.From[Card]().
func (Card) Query() *orm.Query[Card] { return orm.From[Card]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Card].
func (x Card) Delete() (orm.ExecResult, error) { return orm.Unlink[Card](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Card) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Card](tx, x.ID) }
