// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"
)

// Gadget corresponds to model "widgets.gadget".
type Gadget struct {
	ID          string       `db:"id"`
	TenantID    string       `db:"tenant_id"`
	CreatedAt   time.Time    `db:"created_at"`
	UpdatedAt   time.Time    `db:"updated_at"`
	DeletedAt   *time.Time   `db:"deleted_at"`
	CreatedBy   *string      `db:"created_by"`
	Etag        string       `db:"etag"`
	Name        string       `db:"name"`
	DisplayName *string      `db:"display_name"`
	State       *GadgetState `db:"state"`
}

type GadgetState string

const (
	GadgetStateDraft GadgetState = "draft"
	GadgetStateDone  GadgetState = "done"
)
