// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Gadget corresponds to model "widgets.gadget".
type Gadget struct {
	ID          string       `db:"id"`
	TenantID    string       `db:"tenant_id"`
	CreatedAt   time.Time    `db:"created_at"`
	UpdatedAt   time.Time    `db:"updated_at"`
	DeletedAt   *time.Time   `db:"deleted_at"`
	CreatedBy   *string      `db:"created_by"`
	Etag        string       `db:"etag"`
	Name        string       `db:"name"`
	DisplayName *string      `db:"display_name"`
	State       *GadgetState `db:"state"`
}

func (Gadget) ResourceName() string { return "widgets.gadget" }

// GadgetFields is one orm field descriptor per Condition-bearing column.
var GadgetFields = struct {
	ID          orm.Field[Gadget, string]
	TenantID    orm.Field[Gadget, string]
	CreatedAt   orm.TimeField[Gadget]
	UpdatedAt   orm.TimeField[Gadget]
	DeletedAt   orm.TimeField[Gadget]
	CreatedBy   orm.Field[Gadget, string]
	Etag        orm.StringField[Gadget]
	Name        orm.StringField[Gadget]
	DisplayName orm.StringField[Gadget]
	State       orm.Field[Gadget, GadgetState]
}{
	ID:          orm.NewField[Gadget, string]("id"),
	TenantID:    orm.NewField[Gadget, string]("tenant_id"),
	CreatedAt:   orm.NewTimeField[Gadget]("created_at"),
	UpdatedAt:   orm.NewTimeField[Gadget]("updated_at"),
	DeletedAt:   orm.NewTimeField[Gadget]("deleted_at"),
	CreatedBy:   orm.NewField[Gadget, string]("created_by"),
	Etag:        orm.NewStringField[Gadget]("etag"),
	Name:        orm.NewStringField[Gadget]("name"),
	DisplayName: orm.NewStringField[Gadget]("display_name"),
	State:       orm.NewField[Gadget, GadgetState]("state"),
}

// GadgetAllFields is Query[Gadget]'s default Select() list.
var GadgetAllFields = []orm.AnyField[Gadget]{
	GadgetFields.ID,
	GadgetFields.TenantID,
	GadgetFields.CreatedAt,
	GadgetFields.UpdatedAt,
	GadgetFields.DeletedAt,
	GadgetFields.CreatedBy,
	GadgetFields.Etag,
	GadgetFields.Name,
	GadgetFields.DisplayName,
	GadgetFields.State,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Gadget) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Gadget", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Gadget", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Gadget", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["name"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "Name", "string", v)
		}
		x.Name = val
	}
	if v, ok := row["display_name"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "DisplayName", "*string", v)
		}
		x.DisplayName = &val
	}
	if v, ok := row["state"]; ok && v != nil {
		s, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Gadget", "State", "*GadgetState", v)
		}
		val := GadgetState(s)
		x.State = &val
	}
	return nil
}

// GadgetValues is a typed builder for Gadget's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type GadgetValues struct {
	orm.Values[Gadget]
}

func NewGadgetValues() *GadgetValues {
	return &GadgetValues{Values: *orm.NewValues[Gadget]()}
}

func (v *GadgetValues) SetID(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.ID, x)
	return v
}

func (v *GadgetValues) SetTenantID(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.TenantID, x)
	return v
}

func (v *GadgetValues) SetCreatedAt(x time.Time) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.CreatedAt.Field, x)
	return v
}

func (v *GadgetValues) SetUpdatedAt(x time.Time) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.UpdatedAt.Field, x)
	return v
}

func (v *GadgetValues) SetDeletedAt(x time.Time) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.DeletedAt.Field, x)
	return v
}

func (v *GadgetValues) SetCreatedBy(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.CreatedBy, x)
	return v
}

func (v *GadgetValues) SetEtag(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.Etag.Field, x)
	return v
}

func (v *GadgetValues) SetName(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.Name.Field, x)
	return v
}

func (v *GadgetValues) SetDisplayName(x string) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.DisplayName.Field, x)
	return v
}

func (v *GadgetValues) SetState(x GadgetState) *GadgetValues {
	orm.Set(&v.Values, GadgetFields.State, x)
	return v
}

// Query returns a fresh Gadget query — sugar over orm.From[Gadget]().
func (Gadget) Query() *orm.Query[Gadget] { return orm.From[Gadget]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Gadget].
func (x Gadget) Delete() (orm.ExecResult, error) { return orm.Unlink[Gadget](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Gadget) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Gadget](tx, x.ID) }

type GadgetState string

const (
	GadgetStateDraft GadgetState = "draft"
	GadgetStateDone  GadgetState = "done"
)
