// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"
)

// Gizmo corresponds to model "widgets.gizmo".
type Gizmo struct {
	ID        string     `db:"id"`
	TenantID  string     `db:"tenant_id"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
	CreatedBy *string    `db:"created_by"`
	Etag      string     `db:"etag"`
}
