// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// KindMatrix corresponds to model "widgets.kind_matrix".
type KindMatrix struct {
	ID               string                    `db:"id"`
	TenantID         string                    `db:"tenant_id"`
	CreatedAt        time.Time                 `db:"created_at"`
	UpdatedAt        time.Time                 `db:"updated_at"`
	DeletedAt        *time.Time                `db:"deleted_at"`
	CreatedBy        *string                   `db:"created_by"`
	Etag             string                    `db:"etag"`
	CharField        *string                   `db:"char_field"`
	TextField        *string                   `db:"text_field"`
	IntegerField     *int32                    `db:"integer_field"`
	BigintField      *int64                    `db:"bigint_field"`
	FloatField       *float64                  `db:"float_field"`
	DecimalField     *string                   `db:"decimal_field"`
	BooleanField     *bool                     `db:"boolean_field"`
	UUIDField        *string                   `db:"uuid_field"`
	TimestamptzField *time.Time                `db:"timestamptz_field"`
	DateField        *time.Time                `db:"date_field"`
	TimeField        *string                   `db:"time_field"`
	JsonbField       *[]byte                   `db:"jsonb_field"`
	ByteaField       *[]byte                   `db:"bytea_field"`
	SelectionField   *KindMatrixSelectionField `db:"selection_field"`
	EnumField        *KindMatrixEnumField      `db:"enum_field"`
	GadgetID         *string                   `db:"gadget_id"`
	Gadget           orm.Ref[Gadget]           `db:"gadget"`
	SequenceField    *string                   `db:"sequence_field"`
	LinkType         *string                   `db:"link_type"`
	DynamicLinkField *string                   `db:"dynamic_link_field"`
}

func (KindMatrix) ResourceName() string { return "widgets.kind_matrix" }

// KindMatrixFields is one orm field descriptor per Condition-bearing column.
var KindMatrixFields = struct {
	ID               orm.Field[KindMatrix, string]
	TenantID         orm.Field[KindMatrix, string]
	CreatedAt        orm.TimeField[KindMatrix]
	UpdatedAt        orm.TimeField[KindMatrix]
	DeletedAt        orm.TimeField[KindMatrix]
	CreatedBy        orm.Field[KindMatrix, string]
	Etag             orm.StringField[KindMatrix]
	CharField        orm.StringField[KindMatrix]
	TextField        orm.StringField[KindMatrix]
	IntegerField     orm.OrderedField[KindMatrix, int32]
	BigintField      orm.OrderedField[KindMatrix, int64]
	FloatField       orm.OrderedField[KindMatrix, float64]
	DecimalField     orm.OrderedField[KindMatrix, string]
	BooleanField     orm.Field[KindMatrix, bool]
	UUIDField        orm.Field[KindMatrix, string]
	TimestamptzField orm.TimeField[KindMatrix]
	DateField        orm.TimeField[KindMatrix]
	TimeField        orm.Field[KindMatrix, string]
	JsonbField       orm.BytesField[KindMatrix]
	ByteaField       orm.BytesField[KindMatrix]
	SelectionField   orm.Field[KindMatrix, KindMatrixSelectionField]
	EnumField        orm.Field[KindMatrix, KindMatrixEnumField]
	GadgetID         orm.Field[KindMatrix, string]
	SequenceField    orm.Field[KindMatrix, string]
	LinkType         orm.Field[KindMatrix, string]
	DynamicLinkField orm.Field[KindMatrix, string]
}{
	ID:               orm.NewField[KindMatrix, string]("id"),
	TenantID:         orm.NewField[KindMatrix, string]("tenant_id"),
	CreatedAt:        orm.NewTimeField[KindMatrix]("created_at"),
	UpdatedAt:        orm.NewTimeField[KindMatrix]("updated_at"),
	DeletedAt:        orm.NewTimeField[KindMatrix]("deleted_at"),
	CreatedBy:        orm.NewField[KindMatrix, string]("created_by"),
	Etag:             orm.NewStringField[KindMatrix]("etag"),
	CharField:        orm.NewStringField[KindMatrix]("char_field"),
	TextField:        orm.NewStringField[KindMatrix]("text_field"),
	IntegerField:     orm.NewOrderedField[KindMatrix, int32]("integer_field"),
	BigintField:      orm.NewOrderedField[KindMatrix, int64]("bigint_field"),
	FloatField:       orm.NewOrderedField[KindMatrix, float64]("float_field"),
	DecimalField:     orm.NewOrderedField[KindMatrix, string]("decimal_field"),
	BooleanField:     orm.NewField[KindMatrix, bool]("boolean_field"),
	UUIDField:        orm.NewField[KindMatrix, string]("uuid_field"),
	TimestamptzField: orm.NewTimeField[KindMatrix]("timestamptz_field"),
	DateField:        orm.NewTimeField[KindMatrix]("date_field"),
	TimeField:        orm.NewField[KindMatrix, string]("time_field"),
	JsonbField:       orm.NewBytesField[KindMatrix]("jsonb_field"),
	ByteaField:       orm.NewBytesField[KindMatrix]("bytea_field"),
	SelectionField:   orm.NewField[KindMatrix, KindMatrixSelectionField]("selection_field"),
	EnumField:        orm.NewField[KindMatrix, KindMatrixEnumField]("enum_field"),
	GadgetID:         orm.NewField[KindMatrix, string]("gadget_id"),
	SequenceField:    orm.NewField[KindMatrix, string]("sequence_field"),
	LinkType:         orm.NewField[KindMatrix, string]("link_type"),
	DynamicLinkField: orm.NewField[KindMatrix, string]("dynamic_link_field"),
}

// KindMatrixAllFields is Query[KindMatrix]'s default Select() list.
var KindMatrixAllFields = []orm.AnyField[KindMatrix]{
	KindMatrixFields.ID,
	KindMatrixFields.TenantID,
	KindMatrixFields.CreatedAt,
	KindMatrixFields.UpdatedAt,
	KindMatrixFields.DeletedAt,
	KindMatrixFields.CreatedBy,
	KindMatrixFields.Etag,
	KindMatrixFields.CharField,
	KindMatrixFields.TextField,
	KindMatrixFields.IntegerField,
	KindMatrixFields.BigintField,
	KindMatrixFields.FloatField,
	KindMatrixFields.DecimalField,
	KindMatrixFields.BooleanField,
	KindMatrixFields.UUIDField,
	KindMatrixFields.TimestamptzField,
	KindMatrixFields.DateField,
	KindMatrixFields.TimeField,
	KindMatrixFields.JsonbField,
	KindMatrixFields.ByteaField,
	KindMatrixFields.SelectionField,
	KindMatrixFields.EnumField,
	KindMatrixFields.GadgetID,
	KindMatrixFields.SequenceField,
	KindMatrixFields.LinkType,
	KindMatrixFields.DynamicLinkField,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *KindMatrix) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["char_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "CharField", "*string", v)
		}
		x.CharField = &val
	}
	if v, ok := row["text_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "TextField", "*string", v)
		}
		x.TextField = &val
	}
	if v, ok := row["integer_field"]; ok && v != nil {
		val, ok := v.(int64)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "IntegerField", "*int32", v)
		}
		converted := int32(val)
		x.IntegerField = &converted
	}
	if v, ok := row["bigint_field"]; ok && v != nil {
		val, ok := v.(int64)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "BigintField", "*int64", v)
		}
		x.BigintField = &val
	}
	if v, ok := row["float_field"]; ok && v != nil {
		val, ok := v.(float64)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "FloatField", "*float64", v)
		}
		x.FloatField = &val
	}
	if v, ok := row["decimal_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "DecimalField", "*string", v)
		}
		x.DecimalField = &val
	}
	if v, ok := row["boolean_field"]; ok && v != nil {
		val, ok := v.(bool)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "BooleanField", "*bool", v)
		}
		x.BooleanField = &val
	}
	if v, ok := row["uuid_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "UUIDField", "*string", v)
		}
		x.UUIDField = &val
	}
	if v, ok := row["timestamptz_field"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "TimestamptzField", "*time.Time", v)
		}
		x.TimestamptzField = &val
	}
	if v, ok := row["date_field"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "DateField", "*time.Time", v)
		}
		x.DateField = &val
	}
	if v, ok := row["time_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "TimeField", "*string", v)
		}
		x.TimeField = &val
	}
	if v, ok := row["jsonb_field"]; ok && v != nil {
		val, ok := v.([]byte)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "JsonbField", "*[]byte", v)
		}
		x.JsonbField = &val
	}
	if v, ok := row["bytea_field"]; ok && v != nil {
		val, ok := v.([]byte)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "ByteaField", "*[]byte", v)
		}
		x.ByteaField = &val
	}
	if v, ok := row["selection_field"]; ok && v != nil {
		s, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "SelectionField", "*KindMatrixSelectionField", v)
		}
		val := KindMatrixSelectionField(s)
		x.SelectionField = &val
	}
	if v, ok := row["enum_field"]; ok && v != nil {
		s, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "EnumField", "*KindMatrixEnumField", v)
		}
		val := KindMatrixEnumField(s)
		x.EnumField = &val
	}
	if v, ok := row["gadget_id"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "GadgetID", "*string", v)
		}
		x.GadgetID = &val
	}
	if v, ok := row["gadget"]; ok && v != nil {
		nested, ok := v.(map[string]any)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "Gadget", "orm.Ref[Gadget]", v)
		}
		ref := orm.RelationRef{}
		if id, ok := nested["id"].(string); ok {
			ref.ID = id
		}
		if dn, ok := nested["display_name"].(string); ok {
			ref.DisplayName = dn
		}
		x.Gadget = orm.Ref[Gadget]{RelationRef: &ref}
	}
	if v, ok := row["sequence_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "SequenceField", "*string", v)
		}
		x.SequenceField = &val
	}
	if v, ok := row["link_type"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "LinkType", "*string", v)
		}
		x.LinkType = &val
	}
	if v, ok := row["dynamic_link_field"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindMatrix", "DynamicLinkField", "*string", v)
		}
		x.DynamicLinkField = &val
	}
	return nil
}

// KindMatrixValues is a typed builder for KindMatrix's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type KindMatrixValues struct {
	orm.Values[KindMatrix]
}

func NewKindMatrixValues() *KindMatrixValues {
	return &KindMatrixValues{Values: *orm.NewValues[KindMatrix]()}
}

func (v *KindMatrixValues) SetCharField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.CharField.Field, x)
	return v
}

func (v *KindMatrixValues) SetTextField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.TextField.Field, x)
	return v
}

func (v *KindMatrixValues) SetIntegerField(x int32) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.IntegerField.Field, x)
	return v
}

func (v *KindMatrixValues) SetBigintField(x int64) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.BigintField.Field, x)
	return v
}

func (v *KindMatrixValues) SetFloatField(x float64) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.FloatField.Field, x)
	return v
}

func (v *KindMatrixValues) SetDecimalField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.DecimalField.Field, x)
	return v
}

func (v *KindMatrixValues) SetBooleanField(x bool) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.BooleanField, x)
	return v
}

func (v *KindMatrixValues) SetUUIDField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.UUIDField, x)
	return v
}

func (v *KindMatrixValues) SetTimestamptzField(x time.Time) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.TimestamptzField.Field, x)
	return v
}

func (v *KindMatrixValues) SetDateField(x time.Time) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.DateField.Field, x)
	return v
}

func (v *KindMatrixValues) SetTimeField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.TimeField, x)
	return v
}

func (v *KindMatrixValues) SetJsonbField(x []byte) *KindMatrixValues {
	orm.SetBytes(&v.Values, KindMatrixFields.JsonbField, x)
	return v
}

func (v *KindMatrixValues) SetByteaField(x []byte) *KindMatrixValues {
	orm.SetBytes(&v.Values, KindMatrixFields.ByteaField, x)
	return v
}

func (v *KindMatrixValues) SetSelectionField(x KindMatrixSelectionField) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.SelectionField, x)
	return v
}

func (v *KindMatrixValues) SetEnumField(x KindMatrixEnumField) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.EnumField, x)
	return v
}

func (v *KindMatrixValues) SetGadgetID(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.GadgetID, x)
	return v
}

func (v *KindMatrixValues) SetSequenceField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.SequenceField, x)
	return v
}

func (v *KindMatrixValues) SetLinkType(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.LinkType, x)
	return v
}

func (v *KindMatrixValues) SetDynamicLinkField(x string) *KindMatrixValues {
	orm.Set(&v.Values, KindMatrixFields.DynamicLinkField, x)
	return v
}

// Query returns a fresh KindMatrix query — sugar over orm.From[KindMatrix]().
func (KindMatrix) Query() *orm.Query[KindMatrix] { return orm.From[KindMatrix]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[KindMatrix].
func (x KindMatrix) Delete() (orm.ExecResult, error) { return orm.Unlink[KindMatrix](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x KindMatrix) DeleteTx(tx *db.Tx) (orm.ExecResult, error) {
	return orm.UnlinkTx[KindMatrix](tx, x.ID)
}

type KindMatrixSelectionField string

const (
	KindMatrixSelectionFieldA KindMatrixSelectionField = "a"
	KindMatrixSelectionFieldB KindMatrixSelectionField = "b"
)

type KindMatrixEnumField string

const (
	KindMatrixEnumFieldLow    KindMatrixEnumField = "low"
	KindMatrixEnumFieldMedium KindMatrixEnumField = "medium"
	KindMatrixEnumFieldHigh   KindMatrixEnumField = "high"
)
