// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// KindProbe corresponds to model "widgets.kind_probe".
type KindProbe struct {
	ID                string            `db:"id"`
	TenantID          string            `db:"tenant_id"`
	CreatedAt         time.Time         `db:"created_at"`
	UpdatedAt         time.Time         `db:"updated_at"`
	DeletedAt         *time.Time        `db:"deleted_at"`
	CreatedBy         *string           `db:"created_by"`
	Etag              string            `db:"etag"`
	DecimalField      string            `db:"decimal_field"`
	TimestampField    time.Time         `db:"timestamp_field"`
	DateField         time.Time         `db:"date_field"`
	TimeField         string            `db:"time_field"`
	JsonbField        []byte            `db:"jsonb_field"`
	ByteaField        []byte            `db:"bytea_field"`
	IntegerField      int32             `db:"integer_field"`
	FloatField        float64           `db:"float_field"`
	OptionalNote      *string           `db:"optional_note"`
	CreatedByGadgetID *string           `db:"created_by_gadget_id"`
	CreatedByGadget   *orm.RelationRef  `db:"created_by_gadget"`
	Priority          KindProbePriority `db:"priority"`
}

func (KindProbe) ResourceName() string { return "widgets.kind_probe" }

// KindProbeFields is one orm field descriptor per Condition-bearing column.
var KindProbeFields = struct {
	ID                orm.Field[KindProbe, string]
	TenantID          orm.Field[KindProbe, string]
	CreatedAt         orm.TimeField[KindProbe]
	UpdatedAt         orm.TimeField[KindProbe]
	DeletedAt         orm.TimeField[KindProbe]
	CreatedBy         orm.Field[KindProbe, string]
	Etag              orm.StringField[KindProbe]
	DecimalField      orm.OrderedField[KindProbe, string]
	TimestampField    orm.TimeField[KindProbe]
	DateField         orm.TimeField[KindProbe]
	TimeField         orm.Field[KindProbe, string]
	JsonbField        orm.BytesField[KindProbe]
	ByteaField        orm.BytesField[KindProbe]
	IntegerField      orm.OrderedField[KindProbe, int32]
	FloatField        orm.OrderedField[KindProbe, float64]
	OptionalNote      orm.StringField[KindProbe]
	CreatedByGadgetID orm.Field[KindProbe, string]
	Priority          orm.Field[KindProbe, KindProbePriority]
}{
	ID:                orm.NewField[KindProbe, string]("id"),
	TenantID:          orm.NewField[KindProbe, string]("tenant_id"),
	CreatedAt:         orm.NewTimeField[KindProbe]("created_at"),
	UpdatedAt:         orm.NewTimeField[KindProbe]("updated_at"),
	DeletedAt:         orm.NewTimeField[KindProbe]("deleted_at"),
	CreatedBy:         orm.NewField[KindProbe, string]("created_by"),
	Etag:              orm.NewStringField[KindProbe]("etag"),
	DecimalField:      orm.NewOrderedField[KindProbe, string]("decimal_field"),
	TimestampField:    orm.NewTimeField[KindProbe]("timestamp_field"),
	DateField:         orm.NewTimeField[KindProbe]("date_field"),
	TimeField:         orm.NewField[KindProbe, string]("time_field"),
	JsonbField:        orm.NewBytesField[KindProbe]("jsonb_field"),
	ByteaField:        orm.NewBytesField[KindProbe]("bytea_field"),
	IntegerField:      orm.NewOrderedField[KindProbe, int32]("integer_field"),
	FloatField:        orm.NewOrderedField[KindProbe, float64]("float_field"),
	OptionalNote:      orm.NewStringField[KindProbe]("optional_note"),
	CreatedByGadgetID: orm.NewField[KindProbe, string]("created_by_gadget_id"),
	Priority:          orm.NewField[KindProbe, KindProbePriority]("priority"),
}

// KindProbeAllFields is Query[KindProbe]'s default Select() list.
var KindProbeAllFields = []orm.AnyField[KindProbe]{
	KindProbeFields.ID,
	KindProbeFields.TenantID,
	KindProbeFields.CreatedAt,
	KindProbeFields.UpdatedAt,
	KindProbeFields.DeletedAt,
	KindProbeFields.CreatedBy,
	KindProbeFields.Etag,
	KindProbeFields.DecimalField,
	KindProbeFields.TimestampField,
	KindProbeFields.DateField,
	KindProbeFields.TimeField,
	KindProbeFields.JsonbField,
	KindProbeFields.ByteaField,
	KindProbeFields.IntegerField,
	KindProbeFields.FloatField,
	KindProbeFields.OptionalNote,
	KindProbeFields.CreatedByGadgetID,
	KindProbeFields.Priority,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *KindProbe) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindProbe", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindProbe", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindProbe", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["decimal_field"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "DecimalField", "string", v)
		}
		x.DecimalField = val
	}
	if v, ok := row["timestamp_field"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindProbe", "TimestampField", "time.Time", v)
		}
		x.TimestampField = val
	}
	if v, ok := row["date_field"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("KindProbe", "DateField", "time.Time", v)
		}
		x.DateField = val
	}
	if v, ok := row["time_field"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "TimeField", "string", v)
		}
		x.TimeField = val
	}
	if v, ok := row["jsonb_field"]; ok {
		val, ok := v.([]byte)
		if !ok {
			return orm.NewDecodeError("KindProbe", "JsonbField", "[]byte", v)
		}
		x.JsonbField = val
	}
	if v, ok := row["bytea_field"]; ok {
		val, ok := v.([]byte)
		if !ok {
			return orm.NewDecodeError("KindProbe", "ByteaField", "[]byte", v)
		}
		x.ByteaField = val
	}
	if v, ok := row["integer_field"]; ok {
		val, ok := v.(int64)
		if !ok {
			return orm.NewDecodeError("KindProbe", "IntegerField", "int32", v)
		}
		x.IntegerField = int32(val)
	}
	if v, ok := row["float_field"]; ok {
		val, ok := v.(float64)
		if !ok {
			return orm.NewDecodeError("KindProbe", "FloatField", "float64", v)
		}
		x.FloatField = val
	}
	if v, ok := row["optional_note"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "OptionalNote", "*string", v)
		}
		x.OptionalNote = &val
	}
	if v, ok := row["created_by_gadget_id"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "CreatedByGadgetID", "*string", v)
		}
		x.CreatedByGadgetID = &val
	}
	if v, ok := row["created_by_gadget"]; ok && v != nil {
		nested, ok := v.(map[string]any)
		if !ok {
			return orm.NewDecodeError("KindProbe", "CreatedByGadget", "*orm.RelationRef", v)
		}
		ref := orm.RelationRef{}
		if id, ok := nested["id"].(string); ok {
			ref.ID = id
		}
		if dn, ok := nested["display_name"].(string); ok {
			ref.DisplayName = dn
		}
		x.CreatedByGadget = &ref
	}
	if v, ok := row["priority"]; ok {
		s, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("KindProbe", "Priority", "KindProbePriority", v)
		}
		x.Priority = KindProbePriority(s)
	}
	return nil
}

// KindProbeValues is a typed builder for KindProbe's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type KindProbeValues struct {
	orm.Values[KindProbe]
}

func NewKindProbeValues() *KindProbeValues {
	return &KindProbeValues{Values: *orm.NewValues[KindProbe]()}
}

func (v *KindProbeValues) SetID(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.ID, x)
	return v
}

func (v *KindProbeValues) SetTenantID(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.TenantID, x)
	return v
}

func (v *KindProbeValues) SetCreatedAt(x time.Time) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.CreatedAt.Field, x)
	return v
}

func (v *KindProbeValues) SetUpdatedAt(x time.Time) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.UpdatedAt.Field, x)
	return v
}

func (v *KindProbeValues) SetDeletedAt(x time.Time) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.DeletedAt.Field, x)
	return v
}

func (v *KindProbeValues) SetCreatedBy(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.CreatedBy, x)
	return v
}

func (v *KindProbeValues) SetEtag(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.Etag.Field, x)
	return v
}

func (v *KindProbeValues) SetDecimalField(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.DecimalField.Field, x)
	return v
}

func (v *KindProbeValues) SetTimestampField(x time.Time) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.TimestampField.Field, x)
	return v
}

func (v *KindProbeValues) SetDateField(x time.Time) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.DateField.Field, x)
	return v
}

func (v *KindProbeValues) SetTimeField(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.TimeField, x)
	return v
}

func (v *KindProbeValues) SetJsonbField(x []byte) *KindProbeValues {
	orm.SetBytes(&v.Values, KindProbeFields.JsonbField, x)
	return v
}

func (v *KindProbeValues) SetByteaField(x []byte) *KindProbeValues {
	orm.SetBytes(&v.Values, KindProbeFields.ByteaField, x)
	return v
}

func (v *KindProbeValues) SetIntegerField(x int32) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.IntegerField.Field, x)
	return v
}

func (v *KindProbeValues) SetFloatField(x float64) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.FloatField.Field, x)
	return v
}

func (v *KindProbeValues) SetOptionalNote(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.OptionalNote.Field, x)
	return v
}

func (v *KindProbeValues) SetCreatedByGadgetID(x string) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.CreatedByGadgetID, x)
	return v
}

func (v *KindProbeValues) SetPriority(x KindProbePriority) *KindProbeValues {
	orm.Set(&v.Values, KindProbeFields.Priority, x)
	return v
}

type KindProbePriority string

const (
	KindProbePriorityLow    KindProbePriority = "low"
	KindProbePriorityMedium KindProbePriority = "medium"
	KindProbePriorityHigh   KindProbePriority = "high"
)
