// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// KindProbe corresponds to model "widgets.kind_probe".
type KindProbe struct {
	ID                string            `db:"id"`
	TenantID          string            `db:"tenant_id"`
	CreatedAt         time.Time         `db:"created_at"`
	UpdatedAt         time.Time         `db:"updated_at"`
	DeletedAt         *time.Time        `db:"deleted_at"`
	CreatedBy         *string           `db:"created_by"`
	Etag              string            `db:"etag"`
	DecimalField      string            `db:"decimal_field"`
	TimestampField    time.Time         `db:"timestamp_field"`
	DateField         time.Time         `db:"date_field"`
	TimeField         string            `db:"time_field"`
	JsonbField        []byte            `db:"jsonb_field"`
	ByteaField        []byte            `db:"bytea_field"`
	OptionalNote      *string           `db:"optional_note"`
	CreatedByGadgetID *string           `db:"created_by_gadget_id"`
	CreatedByGadget   *orm.RelationRef  `db:"created_by_gadget"`
	Priority          KindProbePriority `db:"priority"`
}

type KindProbePriority string

const (
	KindProbePriorityLow    KindProbePriority = "low"
	KindProbePriorityMedium KindProbePriority = "medium"
	KindProbePriorityHigh   KindProbePriority = "high"
)
