// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Ticket corresponds to model "widgets.ticket".
type Ticket struct {
	ID        string     `db:"id"`
	TenantID  string     `db:"tenant_id"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
	CreatedBy *string    `db:"created_by"`
	Etag      string     `db:"etag"`
	Number    *string    `db:"number"`
}

func (Ticket) ResourceName() string { return "widgets.ticket" }

// TicketFields is one orm field descriptor per Condition-bearing column.
var TicketFields = struct {
	ID        orm.Field[Ticket, string]
	TenantID  orm.Field[Ticket, string]
	CreatedAt orm.TimeField[Ticket]
	UpdatedAt orm.TimeField[Ticket]
	DeletedAt orm.TimeField[Ticket]
	CreatedBy orm.Field[Ticket, string]
	Etag      orm.StringField[Ticket]
	Number    orm.Field[Ticket, string]
}{
	ID:        orm.NewField[Ticket, string]("id"),
	TenantID:  orm.NewField[Ticket, string]("tenant_id"),
	CreatedAt: orm.NewTimeField[Ticket]("created_at"),
	UpdatedAt: orm.NewTimeField[Ticket]("updated_at"),
	DeletedAt: orm.NewTimeField[Ticket]("deleted_at"),
	CreatedBy: orm.NewField[Ticket, string]("created_by"),
	Etag:      orm.NewStringField[Ticket]("etag"),
	Number:    orm.NewField[Ticket, string]("number"),
}

// TicketAllFields is Query[Ticket]'s default Select() list.
var TicketAllFields = []orm.AnyField[Ticket]{
	TicketFields.ID,
	TicketFields.TenantID,
	TicketFields.CreatedAt,
	TicketFields.UpdatedAt,
	TicketFields.DeletedAt,
	TicketFields.CreatedBy,
	TicketFields.Etag,
	TicketFields.Number,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Ticket) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Ticket", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Ticket", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Ticket", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Ticket", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Ticket", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Ticket", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Ticket", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["number"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Ticket", "Number", "*string", v)
		}
		x.Number = &val
	}
	return nil
}

// TicketValues is a typed builder for Ticket's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type TicketValues struct {
	orm.Values[Ticket]
}

func NewTicketValues() *TicketValues {
	return &TicketValues{Values: *orm.NewValues[Ticket]()}
}

func (v *TicketValues) SetNumber(x string) *TicketValues {
	orm.Set(&v.Values, TicketFields.Number, x)
	return v
}

// Query returns a fresh Ticket query — sugar over orm.From[Ticket]().
func (Ticket) Query() *orm.Query[Ticket] { return orm.From[Ticket]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Ticket].
func (x Ticket) Delete() (orm.ExecResult, error) { return orm.Unlink[Ticket](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Ticket) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Ticket](tx, x.ID) }
