// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Widget corresponds to model "widgets.widget".
type Widget struct {
	ID        string     `db:"id"`
	TenantID  string     `db:"tenant_id"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
	CreatedBy *string    `db:"created_by"`
	Etag      string     `db:"etag"`
	Name      string     `db:"name"`
}

func (Widget) ResourceName() string { return "widgets.widget" }

// WidgetFields is one orm field descriptor per Condition-bearing column.
var WidgetFields = struct {
	ID        orm.Field[Widget, string]
	TenantID  orm.Field[Widget, string]
	CreatedAt orm.TimeField[Widget]
	UpdatedAt orm.TimeField[Widget]
	DeletedAt orm.TimeField[Widget]
	CreatedBy orm.Field[Widget, string]
	Etag      orm.StringField[Widget]
	Name      orm.StringField[Widget]
}{
	ID:        orm.NewField[Widget, string]("id"),
	TenantID:  orm.NewField[Widget, string]("tenant_id"),
	CreatedAt: orm.NewTimeField[Widget]("created_at"),
	UpdatedAt: orm.NewTimeField[Widget]("updated_at"),
	DeletedAt: orm.NewTimeField[Widget]("deleted_at"),
	CreatedBy: orm.NewField[Widget, string]("created_by"),
	Etag:      orm.NewStringField[Widget]("etag"),
	Name:      orm.NewStringField[Widget]("name"),
}

// WidgetAllFields is Query[Widget]'s default Select() list.
var WidgetAllFields = []orm.AnyField[Widget]{
	WidgetFields.ID,
	WidgetFields.TenantID,
	WidgetFields.CreatedAt,
	WidgetFields.UpdatedAt,
	WidgetFields.DeletedAt,
	WidgetFields.CreatedBy,
	WidgetFields.Etag,
	WidgetFields.Name,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Widget) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Widget", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Widget", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Widget", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Widget", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Widget", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Widget", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Widget", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["name"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Widget", "Name", "string", v)
		}
		x.Name = val
	}
	return nil
}

// WidgetValues is a typed builder for Widget's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type WidgetValues struct {
	orm.Values[Widget]
}

func NewWidgetValues() *WidgetValues {
	return &WidgetValues{Values: *orm.NewValues[Widget]()}
}

func (v *WidgetValues) SetID(x string) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.ID, x)
	return v
}

func (v *WidgetValues) SetTenantID(x string) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.TenantID, x)
	return v
}

func (v *WidgetValues) SetCreatedAt(x time.Time) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.CreatedAt.Field, x)
	return v
}

func (v *WidgetValues) SetUpdatedAt(x time.Time) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.UpdatedAt.Field, x)
	return v
}

func (v *WidgetValues) SetDeletedAt(x time.Time) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.DeletedAt.Field, x)
	return v
}

func (v *WidgetValues) SetCreatedBy(x string) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.CreatedBy, x)
	return v
}

func (v *WidgetValues) SetEtag(x string) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.Etag.Field, x)
	return v
}

func (v *WidgetValues) SetName(x string) *WidgetValues {
	orm.Set(&v.Values, WidgetFields.Name.Field, x)
	return v
}

// Query returns a fresh Widget query — sugar over orm.From[Widget]().
func (Widget) Query() *orm.Query[Widget] { return orm.From[Widget]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Widget].
func (x Widget) Delete() (orm.ExecResult, error) { return orm.Unlink[Widget](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Widget) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Widget](tx, x.ID) }
