package codegen

import (
	"bytes"
	"cmp"
	"fmt"
	"maps"
	"reflect"
	"regexp"
	"slices"
	"strings"

	abiv1 "github.com/djangbahevans/goerp/contract/abi/v1"
)

const fileHeader = "// Code generated by goerp codegen. DO NOT EDIT.\n"

// crudOps are the EnableOps names that get a generated function, in the
// order they're emitted. preview and pivot get none: usePivotData and the
// form renderer already serve them (typescript-sdk-reference.md §4).
var crudOps = []string{"list", "get", "create", "update", "delete"}

// Generate renders in's TypeScript API client (typescript-sdk-reference.md
// §4). It first validates in's views (Validate), then fails on any two
// routes that derive the same function or hook name, or two different Go
// route body types that share a name. Output depends only on in, so
// unchanged input renders byte-identical output.
func Generate(in *Input) ([]byte, error) {
	if err := Validate(in); err != nil {
		return nil, err
	}

	g := &generator{
		in:         in,
		apiName:    camel(in.Module) + "Api",
		imports:    map[string]map[string]bool{},
		names:      map[string]string{},
		bodyTypes:  map[string]*abiv1.TypeDesc{},
		bodyOrigin: map[string]string{},
		modelTypes: map[string]bool{},
	}
	return g.run()
}

type generator struct {
	in      *Input
	apiName string

	models []Model

	// imports maps an import source to the names imported from it.
	imports map[string]map[string]bool
	// names maps every top-level identifier or API function name the file
	// declares to the route or model that claimed it.
	names map[string]string

	// bodyTypes are the named route body types to declare, by name.
	bodyTypes  map[string]*abiv1.TypeDesc
	bodyOrigin map[string]string
	// modelTypes are the model type names a route body type of the same
	// name resolves to instead of being declared again.
	modelTypes map[string]bool

	apiEntries []string
	hooks      []string
}

// reservedImports are the identifiers the generated file may import; no
// generated declaration may take one.
var reservedImports = []string{
	"apiClient", "resourceApi", "callAction", "toPagedResponse", "ListParams", "PagedResponse", "PagedResponseWire",
	"useRecord", "useInfiniteList", "useAction", "UseRecordOptions", "UseInfiniteListOptions", "ActionOptions",
	"useQuery", "useMutation", "UseQueryOptions", "UseMutationOptions",
}

// typeOnlyImports are the imported names that are types, imported with
// `type`.
var typeOnlyImports = map[string]bool{
	"ListParams": true, "PagedResponse": true, "PagedResponseWire": true,
	"UseRecordOptions": true, "UseInfiniteListOptions": true, "ActionOptions": true,
	"UseQueryOptions": true, "UseMutationOptions": true,
}

func (g *generator) run() ([]byte, error) {
	for _, name := range reservedImports {
		g.names[name] = "an import from @goerp/sdk or @tanstack/react-query"
	}
	if err := g.claim(g.apiName, "the module's API object"); err != nil {
		return nil, err
	}

	g.models = slices.Clone(g.in.Models)
	slices.SortFunc(g.models, func(a, b Model) int { return strings.Compare(a.Name, b.Name) })
	if err := checkActionNames(g.in.Routes); err != nil {
		return nil, err
	}

	var modelDecls bytes.Buffer
	for _, m := range g.models {
		if err := g.renderModelTypes(&modelDecls, m); err != nil {
			return nil, err
		}
	}

	for _, m := range g.models {
		if err := g.planCRUD(m); err != nil {
			return nil, err
		}
	}
	for _, r := range g.functionRoutes() {
		var err error
		if r.Name != "" {
			err = g.planAction(r)
		} else {
			err = g.planRaw(r)
		}
		if err != nil {
			return nil, err
		}
	}

	var out bytes.Buffer
	out.WriteString(fileHeader)
	out.WriteString("\n")
	g.renderImports(&out)

	out.WriteString("\n// ── Model types ─────────────────────────────────────────────────────\n")
	out.WriteString("// Field names are the wire names the engine sends: the model's declared\n")
	out.WriteString("// field names, unchanged.\n")
	out.Write(modelDecls.Bytes())

	if len(g.bodyTypes) > 0 {
		out.WriteString("\n// ── Route body types (engine.Body / engine.Returns) ─────────────────\n")
		for _, n := range slices.Sorted(maps.Keys(g.bodyTypes)) {
			body, err := g.objectBody(g.bodyTypes[n], g.bodyOrigin[n], true, "")
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&out, "\nexport interface %s %s\n", n, body)
		}
	}

	out.WriteString("\n// ── API client ──────────────────────────────────────────────────────\n\n")
	fmt.Fprintf(&out, "export const %s = {\n", g.apiName)
	for _, e := range g.apiEntries {
		out.WriteString(e)
	}
	out.WriteString("};\n")

	if len(g.hooks) > 0 {
		out.WriteString("\n// ── React Query hooks ───────────────────────────────────────────────\n")
		for _, h := range g.hooks {
			out.WriteString("\n")
			out.WriteString(h)
		}
	}

	out.WriteString("\n// ── useModule binding ───────────────────────────────────────────────\n\n")
	out.WriteString("declare module '@goerp/sdk/react' {\n")
	out.WriteString("  interface ModuleApis {\n")
	fmt.Fprintf(&out, "    %s: typeof %s;\n", propertyKey(g.in.Module), g.apiName)
	out.WriteString("  }\n")
	out.WriteString("}\n")

	return out.Bytes(), nil
}

// functionRoutes is the module's routes that get a generated function, in
// a fixed order: actions by model and name, then raw routes by path and
// method. WS and SSE routes, workflow transitions, preview/pivot overrides,
// and CRUD overrides of an op the model's EnableOps already covers are left
// out — the last because the resource registry resolves the CRUD function
// to the override.
func (g *generator) functionRoutes() []Route {
	ops := map[string]map[string]bool{}
	for _, m := range g.models {
		ops[m.Name] = map[string]bool{}
		for _, op := range m.Ops {
			ops[m.Name][op] = true
		}
	}

	var out []Route
	for _, r := range g.in.Routes {
		switch {
		case r.Streaming || r.Websocket:
			continue
		case r.CRUDAction == "workflow_transition":
			continue
		case r.Name == "preview" || r.Name == "pivot":
			continue
		case r.Name != "" && slices.Contains(crudOps, r.Name) && ops[r.Model][r.Name]:
			continue
		}
		out = append(out, r)
	}

	slices.SortStableFunc(out, func(a, b Route) int {
		if isAction, bIsAction := a.Name != "", b.Name != ""; isAction != bIsAction {
			if isAction {
				return -1
			}
			return 1
		}
		if a.Name != "" {
			return cmp.Or(strings.Compare(a.Model, b.Model), strings.Compare(a.Name, b.Name))
		}
		return cmp.Or(strings.Compare(a.Path, b.Path), strings.Compare(a.Method, b.Method))
	})
	return out
}

// checkActionNames fails when two of the module's models declare an
// action of the same name. callAction and useAction address an action as
// "{module}.{name}" alone, so the shell would resolve both generated
// functions to whichever route it finds first.
func checkActionNames(routes []Route) error {
	actions := slices.DeleteFunc(slices.Clone(routes), func(r Route) bool { return r.Name == "" })
	slices.SortFunc(actions, func(a, b Route) int {
		return cmp.Or(strings.Compare(a.Name, b.Name), strings.Compare(a.Model, b.Model))
	})
	for i := 1; i < len(actions); i++ {
		a, b := actions[i-1], actions[i]
		if a.Name == b.Name && a.Model != b.Model {
			return fmt.Errorf("%s and %s share the action name %q, but an action is called by module and name alone — rename one",
				actionOrigin(a), actionOrigin(b), a.Name)
		}
	}
	return nil
}

func actionOrigin(r Route) string {
	if r.CRUDAction == "workflow_transition" {
		return fmt.Sprintf("the workflow transition %q on %s", r.Name, r.Model)
	}
	return fmt.Sprintf("action %q on %s", r.Name, r.Model)
}

// claim records name as declared by origin, failing if another route or
// model already derived it.
func (g *generator) claim(name, origin string) error {
	if !identPattern.MatchString(name) {
		return fmt.Errorf("%s derives %q, which is not a valid TypeScript identifier", origin, name)
	}
	if prior, ok := g.names[name]; ok {
		return fmt.Errorf("%s and %s both derive the name %q — rename one", prior, origin, name)
	}
	g.names[name] = origin
	return nil
}

func (g *generator) use(source string, names ...string) {
	if g.imports[source] == nil {
		g.imports[source] = map[string]bool{}
	}
	for _, n := range names {
		g.imports[source][n] = true
	}
}

func (g *generator) renderImports(out *bytes.Buffer) {
	for _, source := range []string{"@goerp/sdk", "@goerp/sdk/react", "@tanstack/react-query"} {
		set := g.imports[source]
		if len(set) == 0 {
			continue
		}
		var values, types []string
		for n := range set {
			if typeOnlyImports[n] {
				types = append(types, "type "+n)
			} else {
				values = append(values, n)
			}
		}
		slices.Sort(values)
		slices.Sort(types)
		fmt.Fprintf(out, "import { %s } from '%s';\n", strings.Join(append(values, types...), ", "), source)
	}
}

// ── Model types ─────────────────────────────────────────────────────

// fieldTSType is a field kind's TypeScript type — the JSON type the
// engine's ORM routes send it as (typescript-sdk-reference.md §4 "Types"),
// before nullability. ok is false for a kind with no value on a record
// (one2many).
func fieldTSType(f Field) (ts string, ok bool) {
	switch f.Kind {
	case "char", "text", "uuid", "decimal", "timestamptz", "date", "time", "bytea", "sequence",
		"many2one", "dynamic_link":
		return "string", true
	case "integer", "bigint", "float":
		return "number", true
	case "boolean":
		return "boolean", true
	case "selection", "enum":
		if len(f.Values) == 0 {
			return "string", true
		}
		vals := make([]string, len(f.Values))
		for i, v := range f.Values {
			vals[i] = quote(v)
		}
		return strings.Join(vals, " | "), true
	case "one2many":
		return "", false
	default:
		// jsonb, and any kind this generator doesn't know yet.
		return "unknown", true
	}
}

// FieldTSType is the TypeScript type a field of kind gets, before
// nullability, and false for a kind a record never carries — exported for
// the engine's test that checks it against real ORM responses.
func FieldTSType(kind string, values []string) (string, bool) {
	return fieldTSType(Field{Kind: kind, Values: values})
}

func nullable(ts string) string {
	if ts == "unknown" {
		return ts
	}
	return ts + " | null"
}

// renderModelTypes writes m's record type and, when it has a create or
// update op, its create and update types. Record types are type aliases
// rather than interfaces so they satisfy useRecord's
// `T extends Record<string, unknown>` constraint.
func (g *generator) renderModelTypes(out *bytes.Buffer, m Model) error {
	name := modelTypeName(m)
	origin := "model " + m.Name
	if err := g.claim(name, origin); err != nil {
		return err
	}
	g.modelTypes[name] = true

	fmt.Fprintf(out, "\nexport type %s = {\n", name)
	for _, f := range m.Fields {
		ts, ok := fieldTSType(f)
		if !ok {
			continue
		}
		if !f.Required && !f.PrimaryKey {
			ts = nullable(ts)
		}
		fmt.Fprintf(out, "  %s: %s;\n", propertyKey(f.Name), ts)
	}
	out.WriteString("};\n")

	if !slices.Contains(m.Ops, "create") && !slices.Contains(m.Ops, "update") {
		return nil
	}

	createName := name + "Create"
	if err := g.claim(createName, origin); err != nil {
		return err
	}
	out.WriteString("\n// Required fields are required; every other writable field is optional.\n")
	fmt.Fprintf(out, "export type %s = {\n", createName)
	for _, f := range m.Fields {
		ts, ok := fieldTSType(f)
		if !ok || f.Readonly {
			continue
		}
		if !f.Required {
			ts = nullable(ts)
		}
		key := propertyKey(f.Name)
		// The engine numbers a sequence field a create leaves out.
		if !f.Required || f.HasDefault || f.Kind == "sequence" {
			key += "?"
		}
		fmt.Fprintf(out, "  %s: %s;\n", key, ts)
	}
	out.WriteString("};\n")

	if slices.Contains(m.Ops, "update") {
		updateName := name + "Update"
		if err := g.claim(updateName, origin); err != nil {
			return err
		}
		fmt.Fprintf(out, "\nexport type %s = Partial<%s>;\n", updateName, createName)
	}
	return nil
}

// ── Route body types ────────────────────────────────────────────────

// tsType renders d as a TypeScript type on one line, registering every
// named object type it reaches for declaration.
func (g *generator) tsType(d *abiv1.TypeDesc, origin string) (string, error) {
	return g.renderType(d, origin, false, "")
}

// renderType renders d, with an anonymous object's fields on one line, or
// one per line under indent when multiline is set.
func (g *generator) renderType(d *abiv1.TypeDesc, origin string, multiline bool, indent string) (string, error) {
	if d == nil {
		return "unknown", nil
	}
	var ts string
	switch d.Kind {
	case abiv1.TypeKindString:
		ts = "string"
	case abiv1.TypeKindNumber:
		ts = "number"
	case abiv1.TypeKindBoolean:
		ts = "boolean"
	case abiv1.TypeKindArray:
		elem, err := g.renderType(d.Elem, origin, multiline, indent)
		if err != nil {
			return "", err
		}
		if strings.Contains(elem, " | ") {
			elem = "(" + elem + ")"
		}
		ts = elem + "[]"
	case abiv1.TypeKindRecord:
		elem, err := g.renderType(d.Elem, origin, multiline, indent)
		if err != nil {
			return "", err
		}
		ts = "Record<string, " + elem + ">"
	case abiv1.TypeKindObject:
		if d.Name != "" {
			if err := g.registerBodyType(d, origin); err != nil {
				return "", err
			}
			ts = d.Name
			break
		}
		body, err := g.objectBody(d, origin, multiline, indent)
		if err != nil {
			return "", err
		}
		ts = body
	default:
		return "unknown", nil
	}
	if d.Nullable {
		ts = nullable(ts)
	}
	return ts, nil
}

// registerBodyType records a named object type for declaration. A name
// that is one of the module's model types resolves to that type instead:
// engine.Returns[Contact]() on the model's generated Go record struct
// returns the model's own record type.
func (g *generator) registerBodyType(d *abiv1.TypeDesc, origin string) error {
	if g.modelTypes[d.Name] {
		return nil
	}
	shape := *d
	shape.Nullable = false
	if prior, ok := g.bodyTypes[d.Name]; ok {
		if !reflect.DeepEqual(*prior, shape) {
			return fmt.Errorf("%s and %s use two different Go types named %s — rename one", g.bodyOrigin[d.Name], origin, d.Name)
		}
		return nil
	}
	if err := g.claim(d.Name, origin); err != nil {
		return err
	}
	g.bodyTypes[d.Name] = &shape
	g.bodyOrigin[d.Name] = origin
	// Walk the fields now, so nested named types are registered and
	// checked for clashes before rendering starts.
	_, err := g.objectBody(&shape, origin, false, "")
	return err
}

// objectBody renders an object type's fields as a `{ ... }` literal: on
// one line, or one field per line under indent when multiline is set.
func (g *generator) objectBody(d *abiv1.TypeDesc, origin string, multiline bool, indent string) (string, error) {
	if len(d.Fields) == 0 {
		return "{}", nil
	}
	fields := make([]string, len(d.Fields))
	for i, f := range d.Fields {
		ts, err := g.renderType(&f.Type, origin, multiline, indent+"  ")
		if err != nil {
			return "", err
		}
		key := propertyKey(f.Name)
		if f.Optional {
			key += "?"
		}
		fields[i] = key + ": " + ts + ";"
	}
	if !multiline {
		return "{ " + strings.Join(fields, " ") + " }", nil
	}
	var b strings.Builder
	b.WriteString("{\n")
	for _, f := range fields {
		b.WriteString(indent)
		b.WriteString("  ")
		b.WriteString(f)
		b.WriteString("\n")
	}
	b.WriteString(indent)
	b.WriteString("}")
	return b.String(), nil
}

// ── API functions and hooks ─────────────────────────────────────────

func (g *generator) addEntry(comment, name, sig, body string) {
	var b strings.Builder
	for line := range strings.Lines(comment) {
		b.WriteString("  // ")
		b.WriteString(strings.TrimSuffix(line, "\n"))
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "  %s: %s =>\n    %s,\n", name, sig, body)
	g.apiEntries = append(g.apiEntries, b.String())
}

// planCRUD adds m's EnableOps functions and hooks.
func (g *generator) planCRUD(m Model) error {
	name := modelTypeName(m)
	plural := modelPluralName(m)
	res := quote(m.Name)
	origin := func(op string) string { return fmt.Sprintf("EnableOps %s on %s", op, m.Name) }

	var enabled []string
	for _, op := range crudOps {
		if slices.Contains(m.Ops, op) {
			enabled = append(enabled, op)
		}
	}
	if len(enabled) == 0 {
		return nil
	}

	g.use("@goerp/sdk", "resourceApi")
	for i, op := range enabled {
		comment := ""
		if i == 0 {
			comment = fmt.Sprintf("EnableOps CRUD on %s — paths resolve at call time through\nthe resource registry, as useRecord and useInfiniteList resolve them.\n", m.Name)
		}
		var fn, sig, body string
		switch op {
		case "list":
			g.use("@goerp/sdk", "ListParams", "PagedResponse")
			fn = "list" + plural
			sig = fmt.Sprintf("(params?: ListParams<%s>): Promise<PagedResponse<%s>>", name, name)
			body = fmt.Sprintf("resourceApi.list<%s>(%s, params)", name, res)
		case "get":
			fn = "get" + name
			sig = fmt.Sprintf("(id: string): Promise<%s>", name)
			body = fmt.Sprintf("resourceApi.get<%s>(%s, id)", name, res)
		case "create":
			fn = "create" + name
			sig = fmt.Sprintf("(body: %sCreate): Promise<%s>", name, name)
			body = fmt.Sprintf("resourceApi.create<%s>(%s, body)", name, res)
		case "update":
			fn = "update" + name
			sig = fmt.Sprintf("(id: string, body: %sUpdate, expectedEtag?: string): Promise<%s>", name, name)
			body = fmt.Sprintf("resourceApi.update<%s>(%s, id, body, expectedEtag)", name, res)
			comment += "`expectedEtag` is sent as `If-Match`; omit it to write without an\noptimistic-lock check.\n"
		case "delete":
			fn = "delete" + name
			sig = "(id: string): Promise<void>"
			body = fmt.Sprintf("resourceApi.delete(%s, id)", res)
		}
		if err := g.claim(fn, origin(op)); err != nil {
			return err
		}
		g.addEntry(comment, fn, sig, body)
	}

	// CRUD hooks wrap the SDK hooks, so they share the shell renderers'
	// query keys and cache.
	if slices.Contains(enabled, "list") {
		hook := "use" + plural
		if err := g.claim(hook, origin("list")); err != nil {
			return err
		}
		g.use("@goerp/sdk/react", "useInfiniteList", "UseInfiniteListOptions")
		g.hooks = append(g.hooks, fmt.Sprintf(
			"export function %s(options?: UseInfiniteListOptions) {\n  return useInfiniteList<%s>(%s, options);\n}\n",
			hook, name, res))
	}
	if slices.Contains(enabled, "get") {
		hook := "use" + name
		if err := g.claim(hook, origin("get")); err != nil {
			return err
		}
		g.use("@goerp/sdk/react", "useRecord", "UseRecordOptions")
		g.hooks = append(g.hooks, fmt.Sprintf(
			"export function %s(id: string | undefined, options?: UseRecordOptions) {\n  return useRecord<%s>(%s, id, options);\n}\n",
			hook, name, res))
	}
	return nil
}

// responseType renders r's declared response type: the element type for
// a list route, whose function returns PagedResponse of it.
func (g *generator) responseType(r Route, origin string) (res, result, wire string, err error) {
	res, err = g.tsType(r.ResponseType, origin)
	if err != nil {
		return "", "", "", err
	}
	if !r.ResponseIsList {
		return res, res, res, nil
	}
	g.use("@goerp/sdk", "PagedResponse", "PagedResponseWire", "toPagedResponse")
	return res, "PagedResponse<" + res + ">", "PagedResponseWire<" + res + ">", nil
}

// planAction adds an engine.Action route's function and useAction hook.
func (g *generator) planAction(r Route) error {
	origin := actionOrigin(r)

	typeName := pascal(resourceSegment(r.Model))
	fn := camel(r.Name) + typeName
	hook := "use" + pascal(r.Name) + typeName

	req, err := g.tsType(r.RequestType, origin)
	if err != nil {
		return err
	}
	_, result, wire, err := g.responseType(r, origin)
	if err != nil {
		return err
	}

	routeName := quote(g.in.Module + "." + r.Name)
	var sig, vars, arg string
	switch {
	case r.Scope == CollectionScope && r.RequestType != nil:
		sig, vars, arg = "(body: "+req+")", req, "body"
	case r.Scope == CollectionScope:
		sig, vars, arg = "(body?: unknown)", "unknown", "body"
	case r.RequestType != nil:
		sig, vars, arg = "(id: string, body: "+req+")", "{ id: string; body: "+req+" }", "{ id, body }"
	default:
		sig, vars, arg = "(id: string, body?: unknown)", "{ id: string; body?: unknown }", "{ id, body }"
	}

	body := fmt.Sprintf("callAction<%s, %s>(%s, %s)", wire, vars, routeName, arg)
	if r.ResponseIsList {
		body += ".then((wire) => toPagedResponse(wire))"
	}

	if err := g.claim(fn, origin); err != nil {
		return err
	}
	if err := g.claim(hook, origin); err != nil {
		return err
	}
	g.use("@goerp/sdk", "callAction")
	g.addEntry(fmt.Sprintf("action %q on %q, %s scope", r.Name, r.Model, scopeLabel(r.Scope)),
		fn, sig+": Promise<"+result+">", body)

	g.use("@goerp/sdk/react", "useAction", "ActionOptions")
	g.hooks = append(g.hooks, fmt.Sprintf(
		"export function %s(options?: ActionOptions<%s, %s>) {\n  return useAction<%s, %s>(%s, options);\n}\n",
		hook, wire, vars, wire, vars, routeName))
	return nil
}

func scopeLabel(scope string) string {
	if scope == CollectionScope {
		return "collection"
	}
	return "record"
}

var pathParamPattern = regexp.MustCompile(`^\{(.+)\}$`)

// rawParam is one parameter of a raw route's function.
type rawParam struct {
	name     string
	ts       string
	optional bool
}

func (p rawParam) decl() string {
	if p.optional {
		return p.name + "?: " + p.ts
	}
	return p.name + ": " + p.ts
}

// planRaw adds a raw engine.GET/POST/PUT/PATCH/DELETE route's function and
// its useQuery (GET) or useMutation hook.
func (g *generator) planRaw(r Route) error {
	method := strings.ToUpper(r.Method)
	origin := fmt.Sprintf("%s %s", method, r.Path)

	// {method}{PathSegments}: every literal segment in PascalCase, path
	// parameters left out.
	var suffix, path strings.Builder
	var params []rawParam
	// The names the function and its hook use themselves; a path
	// parameter spelled the same way gets a Param suffix.
	used := map[string]bool{"body": true, "params": true, "options": true}
	path.WriteString(g.in.PathPrefix)
	for seg := range strings.SplitSeq(strings.Trim(r.Path, "/"), "/") {
		if seg == "" {
			continue
		}
		path.WriteString("/")
		if m := pathParamPattern.FindStringSubmatch(seg); m != nil {
			p := paramName(m[1])
			if used[p] {
				p += "Param"
			}
			if used[p] {
				return fmt.Errorf("%s: two path parameters both become the TypeScript parameter %q — rename one", origin, p)
			}
			used[p] = true
			params = append(params, rawParam{name: p, ts: "string"})
			path.WriteString("${encodeURIComponent(" + p + ")}")
			continue
		}
		suffix.WriteString(pascal(seg))
		path.WriteString(strings.NewReplacer("`", "\\`", "${", "\\${").Replace(seg))
	}
	if suffix.Len() == 0 {
		suffix.WriteString("Index")
	}
	fn := strings.ToLower(method) + suffix.String()
	hook := "use" + pascal(fn)

	_, result, wire, err := g.responseType(r, origin)
	if err != nil {
		return err
	}

	pathLit := "`" + path.String() + "`"
	var call string
	switch method {
	case "GET", "DELETE":
		params = append(params, rawParam{name: "params", ts: "Record<string, unknown>", optional: true})
		// `params && { params }` rather than `{ params }`: under
		// exactOptionalPropertyTypes a RequestOptions can't carry an
		// explicitly undefined params.
		call = fmt.Sprintf("apiClient.%s<%s>(%s, params && { params })", strings.ToLower(method), wire, pathLit)
	case "POST", "PUT", "PATCH":
		req, err := g.tsType(r.RequestType, origin)
		if err != nil {
			return err
		}
		params = append(params, rawParam{name: "body", ts: req, optional: r.RequestType == nil})
		call = fmt.Sprintf("apiClient.%s<%s>(%s, body)", strings.ToLower(method), wire, pathLit)
	default:
		return fmt.Errorf("%s: unsupported method %q", origin, r.Method)
	}
	if r.ResponseIsList {
		call += ".then((wire) => toPagedResponse(wire))"
	}

	if err := g.claim(fn, origin); err != nil {
		return err
	}
	if err := g.claim(hook, origin); err != nil {
		return err
	}
	g.use("@goerp/sdk", "apiClient")

	decls := make([]string, len(params))
	args := make([]string, len(params))
	for i, p := range params {
		decls[i] = p.decl()
		args[i] = p.name
	}
	comment := fmt.Sprintf("engine.%s(%q), a raw route", method, r.Path)
	if r.ResponseType == nil {
		comment += " with no engine.Returns declared"
	}
	g.addEntry(comment, fn, "("+strings.Join(decls, ", ")+"): Promise<"+result+">", call)

	if method == "GET" {
		// Keyed ['{module}', '{function}', ...args], with a missing params
		// object keyed as null.
		g.use("@tanstack/react-query", "useQuery", "UseQueryOptions")
		key := []string{quote(g.in.Module), quote(fn)}
		for _, p := range params {
			if p.name == "params" {
				key = append(key, "params ?? null")
			} else {
				key = append(key, p.name)
			}
		}
		g.hooks = append(g.hooks, fmt.Sprintf(
			"export function %s(%s, options?: Omit<UseQueryOptions<%s>, 'queryKey' | 'queryFn'>) {\n"+
				"  return useQuery({\n"+
				"    queryKey: [%s],\n"+
				"    queryFn: () => %s.%s(%s),\n"+
				"    ...options,\n"+
				"  });\n"+
				"}\n",
			hook, strings.Join(decls, ", "), result, strings.Join(key, ", "), g.apiName, fn, strings.Join(args, ", ")))
		return nil
	}

	// Other methods: useMutation over the function's own parameters, with
	// no automatic invalidation. When every parameter is optional the
	// variables are too, so mutate() can be called bare.
	g.use("@tanstack/react-query", "useMutation", "UseMutationOptions")
	allOptional := true
	for _, p := range params {
		allOptional = allOptional && p.optional
	}
	vars := "{ " + strings.Join(decls, "; ") + " }"
	callArgs := make([]string, len(params))
	for i, p := range params {
		if allOptional {
			callArgs[i] = "variables ? variables." + p.name + " : undefined"
		} else {
			callArgs[i] = "variables." + p.name
		}
	}
	if allOptional {
		vars += " | void"
	}
	g.hooks = append(g.hooks, fmt.Sprintf(
		"export function %s(options?: Omit<UseMutationOptions<%s, Error, %s>, 'mutationFn'>) {\n"+
			"  return useMutation({\n"+
			"    mutationFn: (variables: %s) => %s.%s(%s),\n"+
			"    ...options,\n"+
			"  });\n"+
			"}\n",
		hook, result, vars, vars, g.apiName, fn, strings.Join(callArgs, ", ")))
	return nil
}
