package session

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// RotateOutcome is the result of a Rotate call — which of
// auth-internals.md §4 "Refresh token rotation"'s branches fired.
type RotateOutcome int

const (
	// rotateUnset is RotateOutcome's zero value — deliberately not a
	// meaningful outcome, so a caller that returns early on an error
	// without setting Outcome (e.g. Issuer.Refresh's own error paths)
	// can never be misread as a successful RotateOK by outcome value
	// alone; err must be checked first, and it is what actually
	// distinguishes "genuine error" from every real outcome below.
	rotateUnset RotateOutcome = iota
	// RotateOK: the presented token was live and has been rotated.
	// RotateResult's other fields are populated.
	RotateOK
	// RotateNotFound: no row matches the presented token's hash at all.
	RotateNotFound
	// RotateFamilyRevoked: the row (or, for a replayed dead token, its
	// family) is already revoked. Nothing further happened.
	RotateFamilyRevoked
	// RotateReplaySameDevice: the presented token was already rotated
	// away, and whoever's presenting it now shares a device_id with
	// whoever currently holds the family — a same-device double-submit,
	// not a second party. Not revoked.
	RotateReplaySameDevice
	// RotateReplayDifferentDevice: the presented token was already
	// rotated away by a different device_id than whoever presents it
	// now — treated as compromise. The entire family has just been
	// revoked as a side effect of this call.
	RotateReplayDifferentDevice
)

// RotateResult is Rotate's outcome. Only populated when Outcome ==
// RotateOK; every other outcome leaves these at their zero value.
type RotateResult struct {
	Outcome RotateOutcome

	UserID          string
	TenantID        string
	MFAMethod       string
	MFAVerifiedAt   *time.Time
	MFACredentialID string
}

// Rotate implements auth-internals.md §4 "Refresh token rotation" as one
// serialized transaction: SELECT ... FOR UPDATE locks the presented
// token's row, so a second concurrent request presenting the same token
// blocks on that lock rather than racing an update, then observes the
// true post-commit state once the first request's transaction ends.
//
// presentedHash is the SHA-256 hex hash of the token the caller sent.
// newSessionID/newHash are the caller-generated replacement session id
// and refresh-token hash — pre-generated by the caller (mirroring
// Insert's caller-supplied id) rather than by Rotate itself, so token
// generation stays in authtoken.Issuer, not this package. requestDeviceID
// is the rotating request's own device_id, or "" if it presented none;
// newExpiresAt is the new row's refresh-token expiry. userAgent/
// ipAddress/countryCode are the rotating request's own (auth-internals.md
// §4 step 7b's INSERT lists these as columns to populate on rotation,
// same as a fresh login) — the new row tracks where the session is
// currently being used, not frozen at whatever the original login saw.
func (s *Store) Rotate(ctx context.Context, presentedHash, newSessionID, newHash, requestDeviceID string, newExpiresAt time.Time, userAgent, ipAddress, countryCode string) (RotateResult, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return RotateResult{Outcome: rotateUnset}, fmt.Errorf("begin rotate transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }() // no-op once committed

	var (
		id, familyID, deviceID, userID, tenantID string
		revokedAt, rotatedAt, mfaVerifiedAt      sql.NullTime
		mfaMethod, mfaCredentialID               sql.NullString
	)
	err = tx.QueryRowContext(ctx, `
		SELECT id, family_id, device_id, user_id, tenant_id, revoked_at, rotated_at,
		       mfa_verified_at, mfa_method, mfa_credential_id
		FROM system.sessions WHERE refresh_hash = $1 FOR UPDATE
	`, presentedHash).Scan(&id, &familyID, &deviceID, &userID, &tenantID, &revokedAt, &rotatedAt,
		&mfaVerifiedAt, &mfaMethod, &mfaCredentialID)
	if errors.Is(err, sql.ErrNoRows) {
		return RotateResult{Outcome: RotateNotFound}, nil
	}
	if err != nil {
		return RotateResult{Outcome: rotateUnset}, fmt.Errorf("look up presented token: %w", err)
	}

	if revokedAt.Valid {
		return RotateResult{Outcome: RotateFamilyRevoked}, nil
	}

	if rotatedAt.Valid {
		outcome, err := s.rotateReplay(ctx, tx, familyID, requestDeviceID)
		if err != nil {
			return RotateResult{Outcome: rotateUnset}, err
		}
		if err := tx.Commit(); err != nil {
			return RotateResult{Outcome: rotateUnset}, fmt.Errorf("commit rotate replay decision: %w", err)
		}
		return RotateResult{Outcome: outcome}, nil
	}

	if _, err := tx.ExecContext(ctx, `UPDATE system.sessions SET rotated_at = NOW() WHERE id = $1`, id); err != nil {
		return RotateResult{Outcome: rotateUnset}, fmt.Errorf("mark old row rotated: %w", err)
	}

	newDeviceID := requestDeviceID
	if newDeviceID == "" {
		newDeviceID = deviceID
	}
	if _, err := tx.ExecContext(ctx, `
		INSERT INTO system.sessions
			(id, user_id, tenant_id, family_id, device_id, refresh_hash, expires_at,
			 user_agent, ip_address, country_code, mfa_verified_at, mfa_method, mfa_credential_id)
		VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8, ''), NULLIF($9, '')::inet, NULLIF($10, ''), $11, NULLIF($12, ''), NULLIF($13, '')::uuid)
	`, newSessionID, userID, tenantID, familyID, newDeviceID, newHash, newExpiresAt,
		userAgent, ipAddress, countryCode, mfaVerifiedAt, mfaMethod, mfaCredentialID); err != nil {
		return RotateResult{Outcome: rotateUnset}, fmt.Errorf("insert rotated row: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return RotateResult{Outcome: rotateUnset}, fmt.Errorf("commit rotation: %w", err)
	}

	result := RotateResult{
		Outcome:  RotateOK,
		UserID:   userID,
		TenantID: tenantID,
	}
	if mfaMethod.Valid {
		result.MFAMethod = mfaMethod.String
	}
	if mfaVerifiedAt.Valid {
		t := mfaVerifiedAt.Time
		result.MFAVerifiedAt = &t
	}
	if mfaCredentialID.Valid {
		result.MFACredentialID = mfaCredentialID.String
	}
	return result, nil
}

// rotateReplay implements the rotated_at-already-set branch: look up
// whoever currently holds the family, then decide same-device
// double-submit vs. cross-device compromise. Runs inside Rotate's own
// transaction — tx is not committed here, Rotate commits once after this
// returns.
func (s *Store) rotateReplay(ctx context.Context, tx *sql.Tx, familyID, requestDeviceID string) (RotateOutcome, error) {
	var currentDeviceID string
	err := tx.QueryRowContext(ctx, `
		SELECT device_id FROM system.sessions
		WHERE family_id = $1 AND revoked_at IS NULL AND rotated_at IS NULL
		FOR UPDATE
	`, familyID).Scan(&currentDeviceID)
	if errors.Is(err, sql.ErrNoRows) {
		// Family already fully revoked by an earlier detection — nothing
		// further to do.
		return RotateFamilyRevoked, nil
	}
	if err != nil {
		return rotateUnset, fmt.Errorf("look up family's current holder: %w", err)
	}

	if requestDeviceID != "" && requestDeviceID == currentDeviceID {
		return RotateReplaySameDevice, nil
	}

	if _, err := tx.ExecContext(ctx, `
		UPDATE system.sessions SET revoked_at = NOW(), revoke_reason = 'security_event'
		WHERE family_id = $1
	`, familyID); err != nil {
		return rotateUnset, fmt.Errorf("revoke compromised family: %w", err)
	}
	return RotateReplayDifferentDevice, nil
}
