// Code generated by goerp codegen. DO NOT EDIT.

import { apiClient, callAction, resourceApi, toPagedResponse, type ListParams, type PagedResponse, type PagedResponseWire } from '@goerp/sdk';
import { useAction, useInfiniteList, useRecord, type ActionOptions, type UseInfiniteListOptions, type UseRecordOptions } from '@goerp/sdk/react';
import { useMutation, useQuery, type UseMutationOptions, type UseQueryOptions } from '@tanstack/react-query';

// ── Model types ─────────────────────────────────────────────────────
// Field names are the wire names the engine sends: the model's declared
// field names, unchanged.

export type Company = {
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  created_by: string | null;
  etag: string;
  name: string;
};

export type Contact = {
  id: string;
  tenant_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  created_by: string | null;
  etag: string;
  type: 'person' | 'company';
  status: 'lead' | 'customer';
  name: string;
  display_name: string | null;
  email: string | null;
  company_id: string | null;
  tier: 'bronze' | 'silver' | 'gold' | null;
  credit_limit: string | null;
  is_active: boolean;
  tags: unknown;
};

// Required fields are required; every other writable field is optional.
export type ContactCreate = {
  type: 'person' | 'company';
  status?: 'lead' | 'customer';
  name: string;
  email?: string | null;
  company_id?: string | null;
  tier?: 'bronze' | 'silver' | 'gold' | null;
  credit_limit?: string | null;
  is_active?: boolean;
  tags?: unknown;
};

export type ContactUpdate = Partial<ContactCreate>;

// ── Route body types (engine.Body / engine.Returns) ─────────────────

export interface CompanyInput {
  name: string;
}

export interface ImportRequest {
  rows: ImportRow[];
  dry_run?: boolean;
  mapping?: Record<string, string>;
}

export interface ImportResult {
  created: number;
  errors: string[];
  finished: string;
}

export interface ImportRow {
  name: string;
  email: string | null;
}

export interface MergeContactsRequest {
  target_id: string;
  source_ids: string[];
}

export interface SearchHit {
  id: string;
  score: number;
}

// ── API client ──────────────────────────────────────────────────────

export const contactsApi = {
  // EnableOps CRUD on contacts.company — paths resolve at call time through
  // the resource registry, as useRecord and useInfiniteList resolve them.
  listCompanies: (params?: ListParams<Company>): Promise<PagedResponse<Company>> =>
    resourceApi.list<Company>('contacts.company', params),
  getCompany: (id: string): Promise<Company> =>
    resourceApi.get<Company>('contacts.company', id),
  // EnableOps CRUD on contacts.contact — paths resolve at call time through
  // the resource registry, as useRecord and useInfiniteList resolve them.
  listContacts: (params?: ListParams<Contact>): Promise<PagedResponse<Contact>> =>
    resourceApi.list<Contact>('contacts.contact', params),
  getContact: (id: string): Promise<Contact> =>
    resourceApi.get<Contact>('contacts.contact', id),
  createContact: (body: ContactCreate): Promise<Contact> =>
    resourceApi.create<Contact>('contacts.contact', body),
  // `expectedEtag` is sent as `If-Match`; omit it to write without an
  // optimistic-lock check.
  updateContact: (id: string, body: ContactUpdate, expectedEtag?: string): Promise<Contact> =>
    resourceApi.update<Contact>('contacts.contact', id, body, expectedEtag),
  deleteContact: (id: string): Promise<void> =>
    resourceApi.delete('contacts.contact', id),
  // action "create" on "contacts.company", collection scope
  createCompany: (body: CompanyInput): Promise<unknown> =>
    callAction<unknown, CompanyInput>('contacts.create', body),
  // action "archive" on "contacts.contact", record scope
  archiveContact: (id: string, body?: unknown): Promise<unknown> =>
    callAction<unknown, { id: string; body?: unknown }>('contacts.archive', { id, body }),
  // action "merge" on "contacts.contact", collection scope
  mergeContact: (body: MergeContactsRequest): Promise<Contact> =>
    callAction<Contact, MergeContactsRequest>('contacts.merge', body),
  // engine.GET("/by-email/{email}"), a raw route
  getByEmail: (email: string, params?: Record<string, unknown>): Promise<Contact> =>
    apiClient.get<Contact>(`/contacts/by-email/${encodeURIComponent(email)}`, params && { params }),
  // engine.DELETE("/cache"), a raw route with no engine.Returns declared
  deleteCache: (params?: Record<string, unknown>): Promise<unknown> =>
    apiClient.delete<unknown>(`/contacts/cache`, params && { params }),
  // engine.GET("/export"), a raw route with no engine.Returns declared
  getExport: (params?: Record<string, unknown>): Promise<unknown> =>
    apiClient.get<unknown>(`/contacts/export`, params && { params }),
  // engine.POST("/import"), a raw route
  postImport: (body: ImportRequest): Promise<ImportResult> =>
    apiClient.post<ImportResult>(`/contacts/import`, body),
  // engine.GET("/search"), a raw route
  getSearch: (params?: Record<string, unknown>): Promise<PagedResponse<SearchHit>> =>
    apiClient.get<PagedResponseWire<SearchHit>>(`/contacts/search`, params && { params }).then((wire) => toPagedResponse(wire)),
};

// ── React Query hooks ───────────────────────────────────────────────

export function useCompanies(options?: UseInfiniteListOptions) {
  return useInfiniteList<Company>('contacts.company', options);
}

export function useCompany(id: string | undefined, options?: UseRecordOptions) {
  return useRecord<Company>('contacts.company', id, options);
}

export function useContacts(options?: UseInfiniteListOptions) {
  return useInfiniteList<Contact>('contacts.contact', options);
}

export function useContact(id: string | undefined, options?: UseRecordOptions) {
  return useRecord<Contact>('contacts.contact', id, options);
}

export function useCreateCompany(options?: ActionOptions<unknown, CompanyInput>) {
  return useAction<unknown, CompanyInput>('contacts.create', options);
}

export function useArchiveContact(options?: ActionOptions<unknown, { id: string; body?: unknown }>) {
  return useAction<unknown, { id: string; body?: unknown }>('contacts.archive', options);
}

export function useMergeContact(options?: ActionOptions<Contact, MergeContactsRequest>) {
  return useAction<Contact, MergeContactsRequest>('contacts.merge', options);
}

export function useGetByEmail(email: string, params?: Record<string, unknown>, options?: Omit<UseQueryOptions<Contact>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['contacts', 'getByEmail', email, params ?? null],
    queryFn: () => contactsApi.getByEmail(email, params),
    ...options,
  });
}

export function useDeleteCache(options?: Omit<UseMutationOptions<unknown, Error, { params?: Record<string, unknown> } | void>, 'mutationFn'>) {
  return useMutation({
    mutationFn: (variables: { params?: Record<string, unknown> } | void) => contactsApi.deleteCache(variables ? variables.params : undefined),
    ...options,
  });
}

export function useGetExport(params?: Record<string, unknown>, options?: Omit<UseQueryOptions<unknown>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['contacts', 'getExport', params ?? null],
    queryFn: () => contactsApi.getExport(params),
    ...options,
  });
}

export function usePostImport(options?: Omit<UseMutationOptions<ImportResult, Error, { body: ImportRequest }>, 'mutationFn'>) {
  return useMutation({
    mutationFn: (variables: { body: ImportRequest }) => contactsApi.postImport(variables.body),
    ...options,
  });
}

export function useGetSearch(params?: Record<string, unknown>, options?: Omit<UseQueryOptions<PagedResponse<SearchHit>>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['contacts', 'getSearch', params ?? null],
    queryFn: () => contactsApi.getSearch(params),
    ...options,
  });
}

// ── useModule binding ───────────────────────────────────────────────

declare module '@goerp/sdk/react' {
  interface ModuleApis {
    contacts: typeof contactsApi;
  }
}
