package module

import (
	"regexp"
	"strings"
	"testing"

	"github.com/djangbahevans/goerp/sdk/go/model"
)

var collapseSpace = regexp.MustCompile(`[ \t]+`)

// normalizeSpaces collapses gofmt's own column-alignment padding (runs
// of spaces between a struct field's name/type/tag) down to one space,
// so an assertion on a generated line's content doesn't have to predict
// gofmt's alignment width across a whole struct.
func normalizeSpaces(s string) string {
	return collapseSpace.ReplaceAllString(s, " ")
}

func TestPascalCase(t *testing.T) {
	tests := []struct{ in, want string }{
		{"id", "ID"},
		{"customer_id", "CustomerID"},
		{"created_at", "CreatedAt"},
		{"url", "URL"},
		{"needs_review", "NeedsReview"},
		{"draft", "Draft"},
		{"name", "Name"},
	}
	for _, tt := range tests {
		if got := pascalCase(tt.in); got != tt.want {
			t.Errorf("pascalCase(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestRenderModelFile_BasicFieldKinds(t *testing.T) {
	m := model.Define("widgets.widget", model.Table("widgets")).
		WithStandardFields().
		Field("name", model.Text().Required()).
		Field("quantity", model.Integer().Required()).
		Field("big_quantity", model.BigInt().Required()).
		Field("weight", model.Float().Required()).
		Field("is_active", model.Boolean().Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.HasPrefix(src, "// Code generated by goerp module generate. DO NOT EDIT.\n") {
		t.Errorf("missing DO NOT EDIT header:\n%s", src)
	}
	if !strings.Contains(src, "type Widget struct {") {
		t.Errorf("struct name = want Widget:\n%s", src)
	}

	wantLines := []string{
		`ID string `,
		`TenantID string `,
		`CreatedAt time.Time `,
		`UpdatedAt time.Time `,
		`DeletedAt *time.Time `,
		`CreatedBy *string `,
		`Etag string `,
		`Name string `,
		`Quantity int32 `,
		`BigQuantity int64 `,
		`Weight float64 `,
		`IsActive bool `,
	}
	for _, want := range wantLines {
		if !strings.Contains(src, want) {
			t.Errorf("output missing field %q:\n%s", want, src)
		}
	}
	if !strings.Contains(src, `"time"`) {
		t.Errorf("output should import \"time\" for TimestampTZ fields:\n%s", src)
	}
}

func TestRenderModelFile_NullableVsRequired(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("id", model.UUID().PrimaryKey()).
		Field("required_name", model.Text().Required()).
		Field("optional_name", model.Text())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "ID string `db:\"id\"`") {
		t.Errorf("primary key should be non-pointer string:\n%s", src)
	}
	if !strings.Contains(src, "RequiredName string `db:\"required_name\"`") {
		t.Errorf("required field should be non-pointer:\n%s", src)
	}
	if !strings.Contains(src, "OptionalName *string `db:\"optional_name\"`") {
		t.Errorf("non-required field should be a pointer:\n%s", src)
	}
}

func TestRenderModelFile_SelectionGeneratesNamedTypeAndConstants(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("state", model.Selection("draft", "needs_review", "done").Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "State GadgetState `db:\"state\"`") {
		t.Errorf("struct field should use the named GadgetState type:\n%s", src)
	}
	if !strings.Contains(src, "type GadgetState string") {
		t.Errorf("missing named type declaration:\n%s", src)
	}
	for _, want := range []string{
		`GadgetStateDraft GadgetState = "draft"`,
		`GadgetStateNeedsReview GadgetState = "needs_review"`,
		`GadgetStateDone GadgetState = "done"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing constant %q:\n%s", want, src)
		}
	}
}

func TestRenderModelFile_EnumResolvesValuesFromSchemaTypes(t *testing.T) {
	m := model.Define("widgets.kind_probe").
		Field("priority", model.Enum("kind_probe_priority_enum").Required())

	types := []model.TypeDeclaration{
		model.EnumType("kind_probe_priority_enum", "low", "high"),
	}

	out, err := renderModelFile(m, types)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "Priority KindProbePriority `db:\"priority\"`") {
		t.Errorf("enum field should use the named KindProbePriority type:\n%s", src)
	}
	if !strings.Contains(src, `KindProbePriorityLow KindProbePriority = "low"`) ||
		!strings.Contains(src, `KindProbePriorityHigh KindProbePriority = "high"`) {
		t.Errorf("missing enum constants:\n%s", src)
	}
}

func TestRenderModelFile_UnknownEnumType_Errors(t *testing.T) {
	m := model.Define("widgets.kind_probe").
		Field("priority", model.Enum("does_not_exist").Required())

	if _, err := renderModelFile(m, nil); err == nil {
		t.Fatal("expected an error for an Enum field naming an undeclared type")
	}
}

func TestRenderModelFile_Many2OneGeneratesFKAndRelationRefExpansion(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("customer_id", model.Many2One("contacts.contact").Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `CustomerID string `+"`db:\"customer_id\"`") {
		t.Errorf("missing FK field:\n%s", src)
	}
	if !strings.Contains(src, `Customer *orm.RelationRef `+"`db:\"customer\"`") {
		t.Errorf("missing *orm.RelationRef expansion field:\n%s", src)
	}
	if !strings.Contains(src, `"github.com/djangbahevans/goerp/sdk/go/orm"`) {
		t.Errorf("output should import sdk/go/orm for RelationRef:\n%s", src)
	}
}

func TestRenderModelFile_DynamicLinkGeneratesTwoPlainFields(t *testing.T) {
	m := model.Define("widgets.attachment").
		Field("reference_type", model.Selection("sales.order", "contacts.contact").Required()).
		Field("reference_id", model.DynamicLink("reference_type").Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `ReferenceType string `+"`db:\"reference_type\"`") {
		t.Errorf("missing plain ReferenceType field:\n%s", src)
	}
	if !strings.Contains(src, `ReferenceID string `+"`db:\"reference_id\"`") {
		t.Errorf("missing plain ReferenceID field:\n%s", src)
	}
	// DynamicLink's sibling Selection field must not also generate its
	// own named-string-type version (go-sdk-reference.md §22
	// "DynamicLink" — it names an existing sibling, not a separate
	// allowlist).
	if strings.Contains(src, "AttachmentReferenceType") {
		t.Errorf("sibling Selection field should not generate a separate named type:\n%s", src)
	}
}

// TestRenderModelFile_TwoDynamicLinkFieldsSharingOneSibling_NoDuplicateField
// pins a real bug a code review caught: two DynamicLink fields (a
// polymorphic link's two ends) naming the same sibling Selection field
// used to emit that sibling's struct field twice — a duplicate field
// name go/format.Source doesn't catch (it only parses/formats, it
// doesn't type-check), so it only ever surfaced as a `go build` failure
// on the generated file.
func TestRenderModelFile_TwoDynamicLinkFieldsSharingOneSibling_NoDuplicateField(t *testing.T) {
	m := model.Define("widgets.link").
		Field("reference_type", model.Selection("widgets.widget", "widgets.gadget").Required()).
		Field("source_id", model.DynamicLink("reference_type").Required()).
		Field("target_id", model.DynamicLink("reference_type").Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if n := strings.Count(src, "ReferenceType string"); n != 1 {
		t.Errorf("ReferenceType field emitted %d times, want exactly 1:\n%s", n, src)
	}
	if !strings.Contains(src, `SourceID string `+"`db:\"source_id\"`") {
		t.Errorf("missing SourceID field:\n%s", src)
	}
	if !strings.Contains(src, `TargetID string `+"`db:\"target_id\"`") {
		t.Errorf("missing TargetID field:\n%s", src)
	}
}

// TestRenderModelFile_Many2OneFieldNotEndingInID_Errors pins a real bug:
// a Many2One field name not ending in "_id" made
// strings.TrimSuffix(f.Name, "_id") a silent no-op, so the generated
// *orm.RelationRef expansion field got the exact same Go name as the FK
// field itself — a duplicate struct field, same failure mode as the
// DynamicLink case above.
func TestRenderModelFile_Many2OneFieldNotEndingInID_Errors(t *testing.T) {
	m := model.Define("hr.employee").
		Field("manager", model.Many2One("hr.employee").Required())

	if _, err := renderModelFile(m, nil); err == nil {
		t.Fatal("expected an error for a Many2One field not ending in \"_id\"")
	}
}

// TestRenderModelFile_Many2OneExpansionCollidesWithSiblingField_Errors
// (goerp#970) pins a real bug: renderModelFile guarded the ResourceName()
// collision and the Many2One "_id"-suffix requirement, but not two
// *fields* on one model whose generated Go names collide.
// go/format.Source only parses and formats — it doesn't type-check — so
// a struct with two fields both named Manager (a manager_id Many2One's
// stripped expansion name landing on an unrelated sibling manager
// field) used to pass straight through as gofmt-clean, non-compiling
// output.
func TestRenderModelFile_Many2OneExpansionCollidesWithSiblingField_Errors(t *testing.T) {
	m := model.Define("hr.employee").
		Field("manager_id", model.Many2One("hr.employee")).
		Field("manager", model.Text())

	_, err := renderModelFile(m, nil)
	if err == nil {
		t.Fatal("expected an error for manager_id's Many2One expansion colliding with the sibling manager field")
	}
	if !strings.Contains(err.Error(), "manager_id") || !strings.Contains(err.Error(), `"manager"`) || !strings.Contains(err.Error(), "Manager") {
		t.Errorf("error = %q, want it to name both manager_id and manager and the colliding Go name Manager", err)
	}
}

// TestRenderModelFile_FieldNamesCollidingOnPascalCase_Errors (goerp#970)
// covers the same guard's other trigger: two field names that are
// spelled differently but PascalCase to the same Go identifier, not
// just the Many2One-expansion-specific case above.
func TestRenderModelFile_FieldNamesCollidingOnPascalCase_Errors(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("display_name", model.Text()).
		Field("display-name", model.Text())

	if _, err := renderModelFile(m, nil); err == nil {
		t.Fatal("expected an error for two field names that PascalCase to the same Go identifier")
	}
}

// TestRenderModelFile_SelectionValueWithNonIdentifierChars pins a real
// bug: pascalCase used to split only on "_", so a Selection/Enum value
// spelled with a hyphen or space (e.g. "in-progress" — nothing in the
// schema DSL rejects that spelling) survived untouched into a generated
// constant name, producing Go source go/format.Source can't parse.
func TestRenderModelFile_SelectionValueWithNonIdentifierChars(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("state", model.Selection("in-progress", "needs review").Required())

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `GadgetStateInProgress GadgetState = "in-progress"`) {
		t.Errorf("missing GadgetStateInProgress constant:\n%s", src)
	}
	if !strings.Contains(src, `GadgetStateNeedsReview GadgetState = "needs review"`) {
		t.Errorf("missing GadgetStateNeedsReview constant:\n%s", src)
	}
}

// TestRenderModelFile_EmptyResourceName_Errors pins a real regression: a
// deleted placeholder helper used to guard an empty resource name and
// fall back to a literal "Model" type name; the replacement pascalCase
// has no such guard, and an empty struct name renders as `type  struct`
// — a confusing go/format.Source parse error instead of a clear one
// naming the actual model.
func TestRenderModelFile_EmptyResourceName_Errors(t *testing.T) {
	m := model.Define("")

	if _, err := renderModelFile(m, nil); err == nil {
		t.Fatal("expected an error for a model with no usable resource name")
	}
}

func TestRenderModelFile_One2ManyIsSkipped(t *testing.T) {
	m := model.Define("contacts.contact").
		Field("address_ids", model.One2Many("contacts.address", "contact_id"))

	out, err := renderModelFile(m, nil)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if strings.Contains(src, "AddressIds") || strings.Contains(src, "AddressIDs") {
		t.Errorf("One2Many field should be skipped entirely:\n%s", src)
	}
}

func TestRenderModelFile_UnsupportedFieldKind_Errors(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("counter", model.Sequence("{year}").Required())

	// Sequence is supported (string) — this test instead pins that an
	// actually-unrecognized FieldKind value surfaces a clear error
	// rather than silently emitting a broken field, by forging one
	// beyond the declared enum's range.
	m.Fields[0].Def.Kind = model.FieldKind(9999)

	if _, err := renderModelFile(m, nil); err == nil {
		t.Fatal("expected an error for an unsupported field kind")
	}
}
