package module

import (
	"bytes"
	"context"
	"encoding/json/v2"
	"fmt"
	"go/format"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/djangbahevans/goerp/sdk/go/model"
	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

const generatedFileHeader = "// Code generated by goerp module generate. DO NOT EDIT.\n\n"

// generateDriverSrc is %q-templated with the target module's schema
// package import path — a throwaway WASI guest whose only job is to
// json-encode schema.Schema to stdout, run under a sandboxed instance
// with no filesystem or network access (collectSchema).
const generateDriverSrc = `package main

import (
	"encoding/json/v2"
	"os"

	%q
)

func main() {
	if err := json.MarshalWrite(os.Stdout, schema.Schema); err != nil {
		panic(err)
	}
}
`

// GenerateOptions configures Generate.
type GenerateOptions struct {
	// Check runs generation in memory and writes nothing. Generate
	// returns a non-nil error naming every stale file instead.
	Check bool
}

// GenerateResult is Generate's outcome on success. Stale lists
// models/*.gen.go paths (relative to dir) that were missing, out of
// date, or orphaned — written/removed on a normal run, left untouched
// (and reported via error, not this field) on a --check run that found
// any.
type GenerateResult struct {
	Stale []string
}

// Generate collects dir's module's schema.Schema by building and
// running its schema package under a sandboxed WASI guest (collectSchema)
// and writes one gofmt-clean models/<resource>.gen.go per declared model,
// deterministically — a file is rewritten only if its content actually
// changes, and a models/*.gen.go file for a model no longer in the
// schema is removed.
func Generate(ctx context.Context, dir string, opts GenerateOptions) (*GenerateResult, error) {
	modulePath, err := moduleImportPath(ctx, dir)
	if err != nil {
		return nil, err
	}

	schemaImportPath := modulePath + "/schema"
	modelsImportPath := modulePath + "/models"

	if err := checkSchemaImportBoundary(ctx, dir, schemaImportPath, modelsImportPath); err != nil {
		return nil, err
	}

	sch, err := collectSchema(ctx, dir, schemaImportPath)
	if err != nil {
		return nil, err
	}

	want := make(map[string][]byte, len(sch.Models))
	owner := make(map[string]string, len(sch.Models))
	for _, m := range sch.Models {
		name := m.ResourceName() + ".gen.go"
		if prior, ok := owner[name]; ok {
			return nil, fmt.Errorf("models/%s: both %q and %q resolve to the same ResourceName() — rename one model", name, prior, m.Name)
		}
		owner[name] = m.Name

		content, err := renderModelFile(m)
		if err != nil {
			return nil, fmt.Errorf("render models/%s: %w", name, err)
		}
		want[name] = content
	}

	modelsDir := filepath.Join(dir, "models")
	existing, err := existingGenFiles(modelsDir)
	if err != nil {
		return nil, err
	}

	var stale []string
	for name, content := range want {
		if cur, ok := existing[name]; !ok || !bytes.Equal(cur, content) {
			stale = append(stale, filepath.Join("models", name))
		}
	}
	for name := range existing {
		if _, ok := want[name]; !ok {
			stale = append(stale, filepath.Join("models", name))
		}
	}
	sort.Strings(stale)

	if opts.Check {
		if len(stale) > 0 {
			return nil, fmt.Errorf("models/ is stale: %s", strings.Join(stale, ", "))
		}
		return &GenerateResult{}, nil
	}

	if len(want) > 0 {
		if err := os.MkdirAll(modelsDir, 0o755); err != nil {
			return nil, fmt.Errorf("create models directory: %w", err)
		}
	}
	for name, content := range want {
		if cur, ok := existing[name]; ok && bytes.Equal(cur, content) {
			continue
		}
		if err := os.WriteFile(filepath.Join(modelsDir, name), content, 0o644); err != nil {
			return nil, fmt.Errorf("write models/%s: %w", name, err)
		}
	}
	for name := range existing {
		if _, ok := want[name]; !ok {
			if err := os.Remove(filepath.Join(modelsDir, name)); err != nil {
				return nil, fmt.Errorf("remove orphaned models/%s: %w", name, err)
			}
		}
	}

	return &GenerateResult{Stale: stale}, nil
}

// renderModelFile is a placeholder shape — one empty exported struct per
// model, named from its ResourceName(). What the struct actually looks
// like per FieldKind (naming, nullability, db tags, Many2One/Selection/
// Enum handling) is goerp#961's job, built on top of this pipeline.
func renderModelFile(m *model.ModelDeclaration) ([]byte, error) {
	structName := exportedPlaceholderName(m.ResourceName())

	var buf bytes.Buffer
	buf.WriteString(generatedFileHeader)
	buf.WriteString("package models\n\n")
	fmt.Fprintf(&buf, "// %s corresponds to model %q.\n", structName, m.Name)
	buf.WriteString("//\n// Field and struct generation per FieldKind is not implemented yet (goerp#961).\n")
	fmt.Fprintf(&buf, "type %s struct{}\n", structName)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

// exportedPlaceholderName capitalizes resource's first letter — not the
// initialism-aware PascalCase conversion goerp#961 will apply, just
// enough to produce a valid, exported placeholder identifier.
func exportedPlaceholderName(resource string) string {
	if resource == "" {
		return "Model"
	}
	r := []rune(resource)
	return strings.ToUpper(string(r[0])) + string(r[1:])
}

// existingGenFiles reads modelsDir's own *.gen.go files, keyed by base
// name. A modelsDir that doesn't exist yet (nothing generated so far)
// is not an error — it reads as an empty map.
func existingGenFiles(modelsDir string) (map[string][]byte, error) {
	entries, err := os.ReadDir(modelsDir)
	if os.IsNotExist(err) {
		return map[string][]byte{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", modelsDir, err)
	}

	out := make(map[string][]byte, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".gen.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(modelsDir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", filepath.Join(modelsDir, e.Name()), err)
		}
		out[e.Name()] = data
	}
	return out, nil
}

// moduleImportPath resolves dir's own module path (the go.mod "module"
// directive) — the prefix schemaImportPath/modelsImportPath and the
// driver's own import of the schema package are built from. `go list -m`
// with no pattern lists every *main* module — one line, unless dir sits
// in a go.work workspace naming more than one, in which case the line
// whose own directory is dir is the one actually rooted there.
func moduleImportPath(ctx context.Context, dir string) (string, error) {
	out, err := runCmdOutput(ctx, dir, nil, "go", "list", "-m", "-f", "{{.Dir}}\t{{.Path}}")
	if err != nil {
		return "", fmt.Errorf("resolve module path: %w", err)
	}

	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) == 1 {
		if fields := strings.SplitN(lines[0], "\t", 2); len(fields) == 2 {
			return fields[1], nil
		}
	}

	// EvalSymlinks, not just Abs: dir and go list's own reported .Dir can
	// reach the same directory through different symlinks (e.g. a
	// TMPDIR that's itself a symlink) and still need to compare equal.
	absDir, err := filepath.EvalSymlinks(dir)
	if err != nil {
		return "", fmt.Errorf("resolve module path: %w", err)
	}
	for _, line := range lines {
		fields := strings.SplitN(line, "\t", 2)
		if len(fields) != 2 {
			continue
		}
		lineDir, err := filepath.EvalSymlinks(fields[0])
		if err == nil && lineDir == absDir {
			return fields[1], nil
		}
	}

	return "", fmt.Errorf("resolve module path: no main module in %s's workspace is rooted at %s", dir, absDir)
}

// checkSchemaImportBoundary enforces the one import-boundary rule from
// the schema package convention (go-sdk-reference.md §22 "Package
// layout") that doesn't already fail for a structural reason: a schema
// package that imports the module's own generated models package. A
// first-run models package that doesn't exist yet fails go list -deps
// itself, which already names the missing import as the cause.
func checkSchemaImportBoundary(ctx context.Context, dir, schemaImportPath, modelsImportPath string) error {
	out, err := runCmdOutput(ctx, dir, nil, "go", "list", "-deps", schemaImportPath)
	if err != nil {
		return err
	}
	for line := range strings.Lines(strings.TrimSpace(out)) {
		if strings.TrimSuffix(line, "\n") == modelsImportPath {
			return fmt.Errorf("schema package %s imports %s: a schema package may import only sdk/go/model and the standard library (go-sdk-reference.md §22 %q)",
				schemaImportPath, modelsImportPath, "Package layout")
		}
	}
	return nil
}

// collectSchema builds dir's schema package into a throwaway WASI driver
// binary and runs it under a sandboxed wazero instance with no
// filesystem or network access (os/exec is non-functional under WASI
// Preview 1 regardless) — the only way to get the real model.Schema
// value a fluent model.Define(...)/model.EnumType(...) builder chain
// produces, without reimplementing Go's own evaluation semantics
// (goerp#959's own "Notes").
func collectSchema(ctx context.Context, dir, schemaImportPath string) (model.Schema, error) {
	scratchDir, err := os.MkdirTemp(dir, ".goerp-generate-driver-*")
	if err != nil {
		return model.Schema{}, fmt.Errorf("create driver scratch directory: %w", err)
	}
	defer os.RemoveAll(scratchDir)

	driverSrc := fmt.Sprintf(generateDriverSrc, schemaImportPath)
	if err := os.WriteFile(filepath.Join(scratchDir, "main.go"), []byte(driverSrc), 0o644); err != nil {
		return model.Schema{}, fmt.Errorf("write driver source: %w", err)
	}

	wasmPath := filepath.Join(scratchDir, "driver.wasm")
	driverPkg := "./" + filepath.Base(scratchDir)

	if err := runCmd(ctx, dir, []string{"GOOS=wasip1", "GOARCH=wasm"}, "go", "build", "-o", wasmPath, driverPkg); err != nil {
		return model.Schema{}, err
	}

	binary, err := os.ReadFile(wasmPath)
	if err != nil {
		return model.Schema{}, fmt.Errorf("read driver binary: %w", err)
	}

	stdout, stderr, err := runWasiCommand(ctx, binary)
	if err != nil {
		return model.Schema{}, fmt.Errorf("run schema driver: %w: %s", err, stderr)
	}

	var sch model.Schema
	if err := json.Unmarshal(stdout, &sch); err != nil {
		return model.Schema{}, fmt.Errorf("decode schema driver output: %w", err)
	}
	return sch, nil
}

// runWasiCommand instantiates binary as a WASI Preview 1 command under a
// fresh, throwaway wazero runtime — WASI (for stdout/stderr capture)
// registered and nothing else: no host ABI, no filesystem preopens, no
// network. The instantiation itself runs "_start", which calls main()
// then proc_exit — err is nil for exit code 0 (wazero's own convention),
// a *sys.ExitError for any other exit code.
func runWasiCommand(ctx context.Context, binary []byte) (stdout, stderr []byte, err error) {
	rt := wazero.NewRuntime(ctx)
	defer rt.Close(ctx)

	if _, err := wasi_snapshot_preview1.Instantiate(ctx, rt); err != nil {
		return nil, nil, fmt.Errorf("instantiate wasi: %w", err)
	}

	compiled, err := rt.CompileModule(ctx, binary)
	if err != nil {
		return nil, nil, fmt.Errorf("compile driver: %w", err)
	}

	var outBuf, errBuf bytes.Buffer
	cfg := wazero.NewModuleConfig().WithStdout(&outBuf).WithStderr(&errBuf)

	if _, err := rt.InstantiateModule(ctx, compiled, cfg); err != nil {
		return nil, errBuf.Bytes(), err
	}

	return outBuf.Bytes(), errBuf.Bytes(), nil
}

// runCmdOutput is runCmd (build.go) plus the subprocess's own stdout,
// separate from the combined stdout+stderr its error message still
// carries on failure.
func runCmdOutput(ctx context.Context, dir string, extraEnv []string, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	if extraEnv != nil {
		cmd.Env = append(os.Environ(), extraEnv...)
	}

	var stdout, combined bytes.Buffer
	cmd.Stdout = io.MultiWriter(&stdout, &combined)
	cmd.Stderr = &combined

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("run %s %s: %w: %s", name, strings.Join(args, " "), err, combined.String())
	}

	return stdout.String(), nil
}
