package module

import (
	"context"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const generateFixtureSchemaOneModel = `package schema

import "github.com/djangbahevans/goerp/sdk/go/model"

var Schema = model.Schema{
	Models: []*model.ModelDeclaration{
		model.Define("widgets.widget", model.Table("widgets")).
			WithStandardFields().
			Field("name", model.Text().Required()),
	},
}
`

const generateFixtureSchemaTwoModels = `package schema

import "github.com/djangbahevans/goerp/sdk/go/model"

var Schema = model.Schema{
	Models: []*model.ModelDeclaration{
		model.Define("widgets.widget", model.Table("widgets")).
			WithStandardFields().
			Field("name", model.Text().Required()),
		model.Define("widgets.gadget", model.Table("gadgets")).
			WithStandardFields().
			Field("name", model.Text().Required()),
	},
}
`

const generateFixtureSchemaResourceNameCollision = `package schema

import "github.com/djangbahevans/goerp/sdk/go/model"

var Schema = model.Schema{
	Models: []*model.ModelDeclaration{
		model.Define("sales.order", model.Table("sales_orders")).
			WithStandardFields(),
		model.Define("purchase.order", model.Table("purchase_orders")).
			WithStandardFields(),
	},
}
`

const generateFixtureSchemaEmpty = `package schema

import "github.com/djangbahevans/goerp/sdk/go/model"

var Schema = model.Schema{}
`

const generateFixtureSchemaCompileError = `package schema

import "github.com/djangbahevans/goerp/sdk/go/model"

var Schema = model.Schema{
	Models: []*model.ModelDeclaration{
		this does not compile,
	},
}
`

func generateFixtureSchemaImportingModels(modulePath string) string {
	return `package schema

import (
	"github.com/djangbahevans/goerp/sdk/go/model"

	_ "` + modulePath + `/models"
)

var Schema = model.Schema{}
`
}

// writeGenerateFixture scaffolds a standalone module at t.TempDir()/demo
// with the given schema/schema.go content, then overlays a go.work
// workspace onto this repo's own checkout so the fixture's schema
// package — which imports sdk/go/model — resolves without needing a
// require in the fixture's own go.mod (Generate itself never touches
// go.mod; this is purely a test-resolution concern, the same one
// scaffold_test.go's TestCreateScaffoldsCompilableSchemaPackage solves
// the same way).
func writeGenerateFixture(t *testing.T, schemaGo string) string {
	t.Helper()

	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}

	dir := filepath.Join(t.TempDir(), "demo_module")
	if err := os.MkdirAll(filepath.Join(dir, "schema"), 0o755); err != nil {
		t.Fatalf("mkdir schema: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module generate-fixture\n\ngo 1.27.0\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "schema", "schema.go"), []byte(schemaGo), 0o644); err != nil {
		t.Fatalf("write schema.go: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	workInit := exec.CommandContext(ctx, "go", "work", "init", ".", repoRoot)
	workInit.Dir = dir
	if out, err := workInit.CombinedOutput(); err != nil {
		t.Fatalf("go work init: %v\n%s", err, out)
	}

	return dir
}

func TestGenerate_EmptySchema_WritesNothing(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaEmpty)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	result, err := Generate(ctx, dir, GenerateOptions{})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(result.Stale) != 0 {
		t.Errorf("Stale = %v, want none", result.Stale)
	}
	if _, err := os.Stat(filepath.Join(dir, "models")); err == nil {
		t.Error("models/ directory was created for an empty schema")
	}
}

func TestGenerate_OneModel_WritesGenFile(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaOneModel)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	result, err := Generate(ctx, dir, GenerateOptions{})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(result.Stale) != 1 || result.Stale[0] != filepath.Join("models", "widget.gen.go") {
		t.Fatalf("Stale = %v, want [models/widget.gen.go]", result.Stale)
	}

	entries, err := os.ReadDir(filepath.Join(dir, "models"))
	if err != nil {
		t.Fatalf("read models dir: %v", err)
	}
	if len(entries) != 1 || entries[0].Name() != "widget.gen.go" {
		t.Fatalf("models/ entries = %v, want exactly [widget.gen.go]", entries)
	}

	data, err := os.ReadFile(filepath.Join(dir, "models", "widget.gen.go"))
	if err != nil {
		t.Fatalf("read widget.gen.go: %v", err)
	}
	if !strings.HasPrefix(string(data), "// Code generated by goerp module generate. DO NOT EDIT.\n") {
		t.Errorf("widget.gen.go missing DO NOT EDIT header:\n%s", data)
	}

	formatted, err := format.Source(data)
	if err != nil {
		t.Fatalf("widget.gen.go is not valid Go: %v\n%s", err, data)
	}
	if string(formatted) != string(data) {
		t.Errorf("widget.gen.go is not gofmt-clean:\ngot:\n%s\nwant:\n%s", data, formatted)
	}
}

func TestGenerate_SecondRunLeavesMtimeUnchanged(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaOneModel)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	if _, err := Generate(ctx, dir, GenerateOptions{}); err != nil {
		t.Fatalf("first Generate: %v", err)
	}

	genFile := filepath.Join(dir, "models", "widget.gen.go")
	before, err := os.Stat(genFile)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}

	// Sleep past most filesystems' mtime resolution so a spurious
	// rewrite would actually be observable.
	time.Sleep(20 * time.Millisecond)

	result, err := Generate(ctx, dir, GenerateOptions{})
	if err != nil {
		t.Fatalf("second Generate: %v", err)
	}
	if len(result.Stale) != 0 {
		t.Errorf("second run's Stale = %v, want none", result.Stale)
	}

	after, err := os.Stat(genFile)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Errorf("widget.gen.go mtime changed: before=%v after=%v", before.ModTime(), after.ModTime())
	}
}

func TestGenerate_Check(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaOneModel)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	if _, err := Generate(ctx, dir, GenerateOptions{}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if _, err := Generate(ctx, dir, GenerateOptions{Check: true}); err != nil {
		t.Fatalf("--check on fresh output: %v", err)
	}

	if err := os.WriteFile(filepath.Join(dir, "schema", "schema.go"), []byte(generateFixtureSchemaTwoModels), 0o644); err != nil {
		t.Fatalf("update schema.go: %v", err)
	}

	_, err := Generate(ctx, dir, GenerateOptions{Check: true})
	if err == nil {
		t.Fatal("--check after a schema change: expected a non-zero error")
	}
	if !strings.Contains(err.Error(), filepath.Join("models", "gadget.gen.go")) {
		t.Errorf("--check error = %q, want it to name models/gadget.gen.go", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "models", "gadget.gen.go")); err == nil {
		t.Error("--check wrote models/gadget.gen.go — it must not write anything")
	}
}

func TestGenerate_OrphanedGenFileIsRemoved(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaTwoModels)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	if _, err := Generate(ctx, dir, GenerateOptions{}); err != nil {
		t.Fatalf("first Generate: %v", err)
	}

	if err := os.WriteFile(filepath.Join(dir, "schema", "schema.go"), []byte(generateFixtureSchemaOneModel), 0o644); err != nil {
		t.Fatalf("update schema.go: %v", err)
	}

	result, err := Generate(ctx, dir, GenerateOptions{})
	if err != nil {
		t.Fatalf("second Generate: %v", err)
	}
	if len(result.Stale) != 1 || result.Stale[0] != filepath.Join("models", "gadget.gen.go") {
		t.Fatalf("Stale = %v, want [models/gadget.gen.go]", result.Stale)
	}

	if _, err := os.Stat(filepath.Join(dir, "models", "gadget.gen.go")); !os.IsNotExist(err) {
		t.Errorf("models/gadget.gen.go still exists after its model left the schema: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "models", "widget.gen.go")); err != nil {
		t.Errorf("models/widget.gen.go should still exist: %v", err)
	}
}

func TestGenerate_SchemaImportingModelsPackage_Fails(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaImportingModels("generate-fixture"))

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	_, err := Generate(ctx, dir, GenerateOptions{})
	if err == nil {
		t.Fatal("expected an error for a schema package importing the module's own models package")
	}
	if !strings.Contains(err.Error(), "generate-fixture/models") {
		t.Errorf("error = %q, want it to name generate-fixture/models", err)
	}
}

func TestGenerate_ResourceNameCollision_Fails(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaResourceNameCollision)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	_, err := Generate(ctx, dir, GenerateOptions{})
	if err == nil {
		t.Fatal("expected an error for two models resolving to the same ResourceName()")
	}
	if !strings.Contains(err.Error(), "order.gen.go") {
		t.Errorf("error = %q, want it to name order.gen.go", err)
	}
	if _, statErr := os.Stat(filepath.Join(dir, "models")); statErr == nil {
		t.Error("models/ was created despite the collision error")
	}
}

func TestGenerate_SchemaCompileError_SurfacesError(t *testing.T) {
	dir := writeGenerateFixture(t, generateFixtureSchemaCompileError)

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	_, err := Generate(ctx, dir, GenerateOptions{})
	if err == nil {
		t.Fatal("expected an error for a schema package with a real compile error")
	}
}
