package module

import (
	"bytes"
	"context"
	"encoding/json/v2"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"github.com/djangbahevans/goerp/sdk/go/model"
	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

const generatedFileHeader = "// Code generated by goerp module generate. DO NOT EDIT.\n\n"

// generateDriverSrc is %q-templated with the target module's schema
// package import path — a throwaway WASI guest whose only job is to
// json-encode schema.Schema to stdout, run under a sandboxed instance
// with no filesystem or network access (collectSchema).
const generateDriverSrc = `package main

import (
	"encoding/json/v2"
	"os"

	%q
)

func main() {
	if err := json.MarshalWrite(os.Stdout, schema.Schema); err != nil {
		panic(err)
	}
}
`

// GenerateOptions configures Generate.
type GenerateOptions struct {
	// Check runs generation in memory and writes nothing. Generate
	// returns a non-nil error naming every stale file instead.
	Check bool
}

// GenerateResult is Generate's outcome on success. Stale lists
// models/*.gen.go paths (relative to dir) that were missing, out of
// date, or orphaned — written/removed on a normal run, left untouched
// (and reported via error, not this field) on a --check run that found
// any.
type GenerateResult struct {
	Stale []string
}

// Generate collects dir's module's schema.Schema by building and
// running its schema package under a sandboxed WASI guest (collectSchema)
// and writes one gofmt-clean models/<resource>.gen.go per declared model,
// deterministically — a file is rewritten only if its content actually
// changes, and a models/*.gen.go file for a model no longer in the
// schema is removed.
func Generate(ctx context.Context, dir string, opts GenerateOptions) (*GenerateResult, error) {
	importPath, err := moduleImportPath(ctx, dir)
	if err != nil {
		return nil, err
	}

	schemaImportPath := importPath + "/schema"
	modelsImportPath := importPath + "/models"

	if err := checkSchemaImportBoundary(ctx, dir, schemaImportPath, modelsImportPath); err != nil {
		return nil, err
	}

	sch, err := collectSchema(ctx, dir, schemaImportPath)
	if err != nil {
		return nil, err
	}

	genCtx, err := loadGenContext(dir, sch)
	if err != nil {
		return nil, err
	}

	want := make(map[string][]byte, len(sch.Models))
	owner := make(map[string]string, len(sch.Models))
	// identifiers is owner's cross-model counterpart: owner catches a
	// filename collision, identifiers catches two models' package-level
	// Go output colliding within the shared models package (goerp#981).
	identifiers := make(map[string]string, len(sch.Models))
	claimIdentifiers := func(owningModel string, ids []string) error {
		for _, id := range ids {
			if prior, ok := identifiers[id]; ok {
				return fmt.Errorf("models/: both %q and %q generate the Go identifier %q — rename one", prior, owningModel, id)
			}
			identifiers[id] = owningModel
		}
		return nil
	}

	var markers []crossModuleMarker
	for _, m := range sch.Models {
		name := m.ResourceName() + ".gen.go"
		if prior, ok := owner[name]; ok {
			return nil, fmt.Errorf("models/%s: both %q and %q resolve to the same ResourceName() — rename one model", name, prior, m.Name)
		}
		owner[name] = m.Name

		// renderModelFile runs first: it catches any within-model naming
		// problem (a field collision, an unnamed field) via its own
		// claimFieldName/writeNamedTypeField checks with a precise,
		// field-level error, before modelPackageIdentifiers's
		// necessarily coarser cross-model check ever sees this model's
		// identifiers.
		content, mks, err := renderModelFile(m, sch.Types, genCtx)
		if err != nil {
			return nil, fmt.Errorf("render models/%s: %w", name, err)
		}

		ids, err := modelPackageIdentifiers(m, sch.Types)
		if err != nil {
			return nil, fmt.Errorf("render models/%s: %w", name, err)
		}
		if err := claimIdentifiers(m.Name, ids); err != nil {
			return nil, err
		}

		want[name] = content
		markers = append(markers, mks...)
	}

	if len(markers) > 0 {
		if prior, ok := owner[crossModuleRefsFileName]; ok {
			return nil, fmt.Errorf("models/%s: reserved for cross-module Many2One markers, but model %q also resolves to it — rename that model", crossModuleRefsFileName, prior)
		}
		owner[crossModuleRefsFileName] = "<cross-module refs>"

		content, deduped, err := renderCrossModuleRefsFile(markers)
		if err != nil {
			return nil, fmt.Errorf("render models/%s: %w", crossModuleRefsFileName, err)
		}
		markerNames := make([]string, len(deduped))
		for i, mk := range deduped {
			markerNames[i] = mk.goName
		}
		if err := claimIdentifiers("<cross-module refs>", markerNames); err != nil {
			return nil, err
		}
		want[crossModuleRefsFileName] = content
	}

	modelsDir := filepath.Join(dir, "models")
	existing, err := existingGenFiles(modelsDir)
	if err != nil {
		return nil, err
	}

	var stale []string
	for name, content := range want {
		if cur, ok := existing[name]; !ok || !bytes.Equal(cur, content) {
			stale = append(stale, filepath.Join("models", name))
		}
	}
	for name := range existing {
		if _, ok := want[name]; !ok {
			stale = append(stale, filepath.Join("models", name))
		}
	}
	sort.Strings(stale)

	if opts.Check {
		if len(stale) > 0 {
			return nil, fmt.Errorf("models/ is stale: %s", strings.Join(stale, ", "))
		}
		return &GenerateResult{}, nil
	}

	if len(want) > 0 {
		if err := os.MkdirAll(modelsDir, 0o755); err != nil {
			return nil, fmt.Errorf("create models directory: %w", err)
		}
	}
	for name, content := range want {
		if cur, ok := existing[name]; ok && bytes.Equal(cur, content) {
			continue
		}
		if err := os.WriteFile(filepath.Join(modelsDir, name), content, 0o644); err != nil {
			return nil, fmt.Errorf("write models/%s: %w", name, err)
		}
	}
	for name := range existing {
		if _, ok := want[name]; !ok {
			if err := os.Remove(filepath.Join(modelsDir, name)); err != nil {
				return nil, fmt.Errorf("remove orphaned models/%s: %w", name, err)
			}
		}
	}

	return &GenerateResult{Stale: stale}, nil
}

// loadGenContext reads dir's manifest.json and combines it with sch's own
// models into the genContext each model file's Many2One fields resolve
// their orm.Ref[T] target against (goerp#979) — the declaring module's own
// name, its sibling models by bare resource name, and its declared
// depends_on/soft_depends_on. It reads the manifest's raw JSON rather than
// the engine's own manifest.Load, the same way BuildFrontend
// (readManifestJSON) does — Generate needs three fields off a manifest
// that may not yet satisfy manifest.Load's full validation (a module
// mid-authoring, or a bare schema-only test fixture), not a fully
// validated Manifest.
func loadGenContext(dir string, sch model.Schema) (genContext, error) {
	decoded, err := readManifestJSON(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return genContext{}, err
	}

	moduleName, _ := decoded["name"].(string)
	if moduleName == "" {
		return genContext{}, fmt.Errorf("manifest is missing name")
	}
	dependsOn := stringSlice(decoded["depends_on"])
	softDependsOn := stringSlice(decoded["soft_depends_on"])

	modelsByResource := make(map[string]*model.ModelDeclaration, len(sch.Models))
	for _, m := range sch.Models {
		modelsByResource[m.ResourceName()] = m
	}

	return genContext{
		moduleName:       moduleName,
		modelsByResource: modelsByResource,
		dependsOn:        dependsOn,
		softDependsOn:    softDependsOn,
	}, nil
}

// stringSlice converts a decoded JSON array value (as readManifestJSON's
// map[string]any yields it) into a []string, skipping any non-string
// element rather than erroring — the same lenient decoding
// readNameVersion already applies to other manifest fields.
func stringSlice(v any) []string {
	arr, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(arr))
	for _, e := range arr {
		if s, ok := e.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

// existingGenFiles reads modelsDir's own *.gen.go files, keyed by base
// name. A modelsDir that doesn't exist yet (nothing generated so far)
// is not an error — it reads as an empty map.
func existingGenFiles(modelsDir string) (map[string][]byte, error) {
	entries, err := os.ReadDir(modelsDir)
	if os.IsNotExist(err) {
		return map[string][]byte{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", modelsDir, err)
	}

	out := make(map[string][]byte, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".gen.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(modelsDir, e.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", filepath.Join(modelsDir, e.Name()), err)
		}
		out[e.Name()] = data
	}
	return out, nil
}

// moduleImportPath resolves dir's own Go import path: the enclosing
// module's own path (the go.mod "module" directive) joined with dir's
// position under that module's root. dir is not always a module root
// itself — a real GoERP module scaffolded by `goerp module create` is,
// but the SDK's own in-repo fixture (sdk/go/modeltest/testdata/fixture)
// is a subdirectory of this repo's own module, and schemaImportPath/
// modelsImportPath must reflect that or the driver's own import of the
// schema package resolves to the wrong package entirely.
//
// `go list -m` with no pattern lists every *main* module — one line,
// unless dir sits in a go.work workspace naming more than one. Every
// line whose own directory contains dir is a candidate (a workspace can
// list one main module nested inside another's directory tree); the
// most specific — the one whose own directory is deepest, i.e. longest
// — is the one that actually governs dir.
func moduleImportPath(ctx context.Context, dir string) (string, error) {
	out, err := runCmdOutput(ctx, dir, nil, "go", "list", "-m", "-f", "{{.Dir}}\t{{.Path}}")
	if err != nil {
		return "", fmt.Errorf("resolve module path: %w", err)
	}

	// Abs before resolveSymlinksOrSelf: dir may be relative (e.g. "." or
	// a caller-relative path), and EvalSymlinks doesn't itself
	// absolutize — it only resolves the symlinks in whatever path it's
	// given. Both steps matter: Abs so a relative dir compares correctly
	// against go list's own absolute .Dir, symlink resolution so the two
	// sides agree even when reached through different symlinks (e.g. a
	// symlinked TMPDIR).
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolve module path: %w", err)
	}
	absDir = resolveSymlinksOrSelf(absDir)

	var bestModDir, bestModPath string
	for line := range strings.Lines(strings.TrimSpace(out)) {
		fields := strings.SplitN(strings.TrimSuffix(line, "\n"), "\t", 2)
		if len(fields) != 2 {
			continue
		}
		modDir := resolveSymlinksOrSelf(fields[0])
		if rel, err := filepath.Rel(modDir, absDir); err != nil || strings.HasPrefix(rel, "..") {
			continue
		}
		if len(modDir) > len(bestModDir) {
			bestModDir, bestModPath = modDir, fields[1]
		}
	}
	if bestModDir == "" {
		return "", fmt.Errorf("resolve module path: no main module in %s's workspace contains %s", dir, absDir)
	}

	return joinModuleAndSubdir(bestModPath, bestModDir, absDir)
}

// resolveSymlinksOrSelf resolves path's own symlinks, or returns path
// unchanged if that fails (e.g. it doesn't exist) — the two dir-related
// paths moduleImportPath compares (absDir, and each candidate module's
// own .Dir) both need this same treatment to agree.
func resolveSymlinksOrSelf(path string) string {
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		return resolved
	}
	return path
}

// joinModuleAndSubdir appends absDir's own position under modDir (an
// already-symlink-resolved module root) to modPath, using Go's forward-
// slash import-path separator regardless of OS.
func joinModuleAndSubdir(modPath, modDir, absDir string) (string, error) {
	rel, err := filepath.Rel(modDir, absDir)
	if err != nil {
		return "", fmt.Errorf("resolve module path: %w", err)
	}
	if rel == "." {
		return modPath, nil
	}
	return modPath + "/" + filepath.ToSlash(rel), nil
}

// checkSchemaImportBoundary enforces the one import-boundary rule from
// the schema package convention (go-sdk-reference.md §22 "Package
// layout") that doesn't already fail for a structural reason: a schema
// package that imports the module's own generated models package. A
// first-run models package that doesn't exist yet fails go list -deps
// itself, which already names the missing import as the cause.
func checkSchemaImportBoundary(ctx context.Context, dir, schemaImportPath, modelsImportPath string) error {
	out, err := runCmdOutput(ctx, dir, nil, "go", "list", "-deps", schemaImportPath)
	if err != nil {
		return err
	}
	for line := range strings.Lines(strings.TrimSpace(out)) {
		if strings.TrimSuffix(line, "\n") == modelsImportPath {
			return fmt.Errorf("schema package %s imports %s: a schema package may import only sdk/go/model and the standard library (go-sdk-reference.md §22 %q)",
				schemaImportPath, modelsImportPath, "Package layout")
		}
	}
	return nil
}

// collectSchema builds dir's schema package into a throwaway WASI driver
// binary and runs it under a sandboxed wazero instance with no
// filesystem or network access (os/exec is non-functional under WASI
// Preview 1 regardless) — the only way to get the real model.Schema
// value a fluent model.Define(...)/model.EnumType(...) builder chain
// produces, without reimplementing Go's own evaluation semantics
// (goerp#959's own "Notes").
func collectSchema(ctx context.Context, dir, schemaImportPath string) (model.Schema, error) {
	scratchDir, err := os.MkdirTemp(dir, ".goerp-generate-driver-*")
	if err != nil {
		return model.Schema{}, fmt.Errorf("create driver scratch directory: %w", err)
	}
	defer os.RemoveAll(scratchDir)

	driverSrc := fmt.Sprintf(generateDriverSrc, schemaImportPath)
	if err := os.WriteFile(filepath.Join(scratchDir, "main.go"), []byte(driverSrc), 0o644); err != nil {
		return model.Schema{}, fmt.Errorf("write driver source: %w", err)
	}

	// wasmPath must be absolute: runCmd sets cmd.Dir to dir, so a path
	// already joined with dir (scratchDir is dir + a generated suffix)
	// would otherwise be resolved relative to dir a second time — the
	// same double-join bug wasmbuild.go's own BuildWasm comment warns
	// about, hit for real here since dir isn't always the caller's cwd.
	wasmPath, err := filepath.Abs(filepath.Join(scratchDir, "driver.wasm"))
	if err != nil {
		return model.Schema{}, fmt.Errorf("resolve driver binary path: %w", err)
	}
	driverPkg := "./" + filepath.Base(scratchDir)

	if err := runCmd(ctx, dir, []string{"GOOS=wasip1", "GOARCH=wasm"}, "go", "build", "-o", wasmPath, driverPkg); err != nil {
		return model.Schema{}, err
	}

	binary, err := os.ReadFile(wasmPath)
	if err != nil {
		return model.Schema{}, fmt.Errorf("read driver binary: %w", err)
	}

	stdout, stderr, err := runWasiCommand(ctx, binary)
	if err != nil {
		return model.Schema{}, fmt.Errorf("run schema driver: %w: %s", err, stderr)
	}

	var sch model.Schema
	if err := json.Unmarshal(stdout, &sch); err != nil {
		return model.Schema{}, fmt.Errorf("decode schema driver output: %w", err)
	}
	return sch, nil
}

// runWasiCommand instantiates binary as a WASI Preview 1 command under a
// fresh, throwaway wazero runtime — WASI (for stdout/stderr capture)
// registered and nothing else: no host ABI, no filesystem preopens, no
// network. The instantiation itself runs "_start", which calls main()
// then proc_exit — err is nil for exit code 0 (wazero's own convention),
// a *sys.ExitError for any other exit code.
func runWasiCommand(ctx context.Context, binary []byte) (stdout, stderr []byte, err error) {
	rt := wazero.NewRuntime(ctx)
	defer rt.Close(ctx)

	if _, err := wasi_snapshot_preview1.Instantiate(ctx, rt); err != nil {
		return nil, nil, fmt.Errorf("instantiate wasi: %w", err)
	}

	compiled, err := rt.CompileModule(ctx, binary)
	if err != nil {
		return nil, nil, fmt.Errorf("compile driver: %w", err)
	}

	var outBuf, errBuf bytes.Buffer
	cfg := wazero.NewModuleConfig().WithStdout(&outBuf).WithStderr(&errBuf)

	if _, err := rt.InstantiateModule(ctx, compiled, cfg); err != nil {
		return nil, errBuf.Bytes(), err
	}

	return outBuf.Bytes(), errBuf.Bytes(), nil
}

// runCmdOutput is runCmd (build.go) plus the subprocess's own stdout,
// separate from the combined stdout+stderr its error message still
// carries on failure.
func runCmdOutput(ctx context.Context, dir string, extraEnv []string, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	if extraEnv != nil {
		cmd.Env = append(os.Environ(), extraEnv...)
	}

	var stdout bytes.Buffer
	var combined syncBuffer
	cmd.Stdout = io.MultiWriter(&stdout, &combined)
	cmd.Stderr = &combined

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("run %s %s: %w: %s", name, strings.Join(args, " "), err, combined.String())
	}

	return stdout.String(), nil
}

// syncBuffer is a bytes.Buffer safe for concurrent writes — os/exec pumps
// Stdout and Stderr on separate goroutines whenever either isn't a raw
// *os.File, so a buffer shared between the two (as combined is above,
// via Stdout's io.MultiWriter and Stderr directly) needs its own lock
// rather than bytes.Buffer's own none.
type syncBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *syncBuffer) Write(p []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(p)
}

func (b *syncBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}
