package module

import (
	"regexp"
	"strings"
	"testing"

	"github.com/djangbahevans/goerp/sdk/go/model"
)

var collapseSpace = regexp.MustCompile(`[ \t]+`)

// testGenContext is the genContext most renderModelFile tests render
// against: a "widgets" module depending on "contacts" and "hr", covering
// every cross-module target these tests reference. Tests exercising a
// same-module Many2One target (goerp#979) build their own genContext with
// a populated modelsByResource instead.
func testGenContext() genContext {
	return genContext{moduleName: "widgets", dependsOn: []string{"contacts", "hr"}}
}

// normalizeSpaces collapses gofmt's own column-alignment padding (runs
// of spaces between a struct field's name/type/tag) down to one space,
// so an assertion on a generated line's content doesn't have to predict
// gofmt's alignment width across a whole struct.
func normalizeSpaces(s string) string {
	return collapseSpace.ReplaceAllString(s, " ")
}

func TestPascalCase(t *testing.T) {
	tests := []struct{ in, want string }{
		{"id", "ID"},
		{"customer_id", "CustomerID"},
		{"created_at", "CreatedAt"},
		{"url", "URL"},
		{"needs_review", "NeedsReview"},
		{"draft", "Draft"},
		{"name", "Name"},
	}
	for _, tt := range tests {
		if got := pascalCase(tt.in); got != tt.want {
			t.Errorf("pascalCase(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestRenderModelFile_BasicFieldKinds(t *testing.T) {
	m := model.Define("widgets.widget", model.Table("widgets")).
		WithStandardFields().
		Field("name", model.Text().Required()).
		Field("quantity", model.Integer().Required()).
		Field("big_quantity", model.BigInt().Required()).
		Field("weight", model.Float().Required()).
		Field("is_active", model.Boolean().Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.HasPrefix(src, "// Code generated by goerp module generate. DO NOT EDIT.\n") {
		t.Errorf("missing DO NOT EDIT header:\n%s", src)
	}
	if !strings.Contains(src, "type Widget struct {") {
		t.Errorf("struct name = want Widget:\n%s", src)
	}

	wantLines := []string{
		`ID string `,
		`TenantID string `,
		`CreatedAt time.Time `,
		`UpdatedAt time.Time `,
		`DeletedAt *time.Time `,
		`CreatedBy *string `,
		`Etag string `,
		`Name string `,
		`Quantity int32 `,
		`BigQuantity int64 `,
		`Weight float64 `,
		`IsActive bool `,
	}
	for _, want := range wantLines {
		if !strings.Contains(src, want) {
			t.Errorf("output missing field %q:\n%s", want, src)
		}
	}
	if !strings.Contains(src, `"time"`) {
		t.Errorf("output should import \"time\" for TimestampTZ fields:\n%s", src)
	}
}

func TestRenderModelFile_NullableVsRequired(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("id", model.UUID().PrimaryKey()).
		Field("required_name", model.Text().Required()).
		Field("optional_name", model.Text())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "ID string `db:\"id\"`") {
		t.Errorf("primary key should be non-pointer string:\n%s", src)
	}
	if !strings.Contains(src, "RequiredName string `db:\"required_name\"`") {
		t.Errorf("required field should be non-pointer:\n%s", src)
	}
	if !strings.Contains(src, "OptionalName *string `db:\"optional_name\"`") {
		t.Errorf("non-required field should be a pointer:\n%s", src)
	}
}

func TestRenderModelFile_SelectionGeneratesNamedTypeAndConstants(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("state", model.Selection("draft", "needs_review", "done").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "State GadgetState `db:\"state\"`") {
		t.Errorf("struct field should use the named GadgetState type:\n%s", src)
	}
	if !strings.Contains(src, "type GadgetState string") {
		t.Errorf("missing named type declaration:\n%s", src)
	}
	for _, want := range []string{
		`GadgetStateDraft GadgetState = "draft"`,
		`GadgetStateNeedsReview GadgetState = "needs_review"`,
		`GadgetStateDone GadgetState = "done"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing constant %q:\n%s", want, src)
		}
	}
}

func TestRenderModelFile_EnumResolvesValuesFromSchemaTypes(t *testing.T) {
	m := model.Define("widgets.kind_probe").
		Field("priority", model.Enum("kind_probe_priority_enum").Required())

	types := []model.TypeDeclaration{
		model.EnumType("kind_probe_priority_enum", "low", "high"),
	}

	out, _, err := renderModelFile(m, types, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "Priority KindProbePriority `db:\"priority\"`") {
		t.Errorf("enum field should use the named KindProbePriority type:\n%s", src)
	}
	if !strings.Contains(src, `KindProbePriorityLow KindProbePriority = "low"`) ||
		!strings.Contains(src, `KindProbePriorityHigh KindProbePriority = "high"`) {
		t.Errorf("missing enum constants:\n%s", src)
	}
}

func TestRenderModelFile_UnknownEnumType_Errors(t *testing.T) {
	m := model.Define("widgets.kind_probe").
		Field("priority", model.Enum("does_not_exist").Required())

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for an Enum field naming an undeclared type")
	}
}

func TestRenderModelFile_Many2OneCrossModuleGeneratesFKAndMarkerRefExpansion(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("customer_id", model.Many2One("contacts.contact").Required())

	out, markers, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `CustomerID string `+"`db:\"customer_id\"`") {
		t.Errorf("missing FK field:\n%s", src)
	}
	if !strings.Contains(src, `Customer orm.Ref[ContactsContactRef] `+"`db:\"customer\"`") {
		t.Errorf("missing orm.Ref[ContactsContactRef] expansion field:\n%s", src)
	}
	if !strings.Contains(src, `"github.com/djangbahevans/goerp/sdk/go/orm"`) {
		t.Errorf("output should import sdk/go/orm for Ref:\n%s", src)
	}

	if len(markers) != 1 || markers[0].goName != "ContactsContactRef" || markers[0].resourceName != "contacts.contact" {
		t.Errorf("markers = %+v, want one {ContactsContactRef, contacts.contact}", markers)
	}
}

// TestRenderCrossModuleRefsFile_DistinctResourcesCollidingOnGoName_Errors
// pins a real bug a code review caught: pascalCase(module)+
// pascalCase(resource) isn't injective — "a_b"+"c" and "a"+"b_c" both
// produce "ABC" — so deduping crossModuleMarker entries by goName alone
// would silently collapse two distinct cross-module targets into one
// marker type, defeating the whole point of a typed Ref[T] for whichever
// target got dropped. A same-goName run must error unless every entry
// also shares the same resourceName (a true duplicate reference, safe to
// dedup).
func TestRenderCrossModuleRefsFile_DistinctResourcesCollidingOnGoName_Errors(t *testing.T) {
	markers := []crossModuleMarker{
		{goName: "ABCRef", resourceName: "a_b.c"},
		{goName: "ABCRef", resourceName: "a.b_c"},
	}

	if _, err := renderCrossModuleRefsFile(markers); err == nil {
		t.Fatal("expected an error for two distinct related_model values colliding on the same generated Go name")
	}
}

// TestRenderCrossModuleRefsFile_SameResourceReferencedTwice_Dedups pins
// the safe case the collision guard above must not reject: the same
// cross-module target referenced by more than one Many2One field
// generates exactly one marker type, not a duplicate declaration.
func TestRenderCrossModuleRefsFile_SameResourceReferencedTwice_Dedups(t *testing.T) {
	markers := []crossModuleMarker{
		{goName: "ContactsContactRef", resourceName: "contacts.contact"},
		{goName: "ContactsContactRef", resourceName: "contacts.contact"},
	}

	out, err := renderCrossModuleRefsFile(markers)
	if err != nil {
		t.Fatalf("renderCrossModuleRefsFile: %v", err)
	}
	if n := strings.Count(string(out), "type ContactsContactRef struct{}"); n != 1 {
		t.Errorf("ContactsContactRef declared %d times, want exactly 1:\n%s", n, out)
	}
}

// TestRenderModelFile_Many2OneSameModuleGeneratesRealTargetStruct pins
// goerp#979's other half: a same-module Many2One target (its related_model
// belongs to the declaring model's own module) resolves Ref[T] to that
// target's own generated struct name, not a marker — and generates no
// crossModuleMarker to collect.
func TestRenderModelFile_Many2OneSameModuleGeneratesRealTargetStruct(t *testing.T) {
	gadget := model.Define("widgets.gadget").
		Field("name", model.Text())
	probe := model.Define("widgets.kind_probe").
		Field("created_by_gadget_id", model.Many2One("widgets.gadget"))

	ctx := genContext{
		moduleName:       "widgets",
		modelsByResource: map[string]*model.ModelDeclaration{"gadget": gadget},
	}

	out, markers, err := renderModelFile(probe, nil, ctx)
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `CreatedByGadget orm.Ref[Gadget] `+"`db:\"created_by_gadget\"`") {
		t.Errorf("missing orm.Ref[Gadget] expansion field:\n%s", src)
	}
	if len(markers) != 0 {
		t.Errorf("markers = %+v, want none for a same-module target", markers)
	}
}

// TestRenderModelFile_Many2OneCrossModuleTargetNotInDependsOn_Errors pins
// that a cross-module target must belong to a module the declaring
// module's manifest actually lists (go-sdk-reference.md §22 "Many2One") —
// generate fails fast rather than emitting a marker for an undeclared
// dependency.
func TestRenderModelFile_Many2OneCrossModuleTargetNotInDependsOn_Errors(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("owner_id", model.Many2One("nobody.person").Required())

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for a cross-module target whose module isn't in depends_on or soft_depends_on")
	}
}

// TestRenderModelFile_Many2OneSameModuleTargetNotDeclared_Errors pins the
// same-module counterpart: a related_model naming the declaring module's
// own name but a resource that module doesn't actually declare.
func TestRenderModelFile_Many2OneSameModuleTargetNotDeclared_Errors(t *testing.T) {
	m := model.Define("widgets.kind_probe").
		Field("created_by_gadget_id", model.Many2One("widgets.gadget").Required())

	ctx := genContext{moduleName: "widgets", modelsByResource: map[string]*model.ModelDeclaration{}}

	if _, _, err := renderModelFile(m, nil, ctx); err == nil {
		t.Fatal("expected an error for a same-module target not declared in this module's own schema")
	}
}

func TestRenderModelFile_DynamicLinkGeneratesTwoPlainFields(t *testing.T) {
	m := model.Define("widgets.attachment").
		Field("reference_type", model.Selection("sales.order", "contacts.contact").Required()).
		Field("reference_id", model.DynamicLink("reference_type").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `ReferenceType string `+"`db:\"reference_type\"`") {
		t.Errorf("missing plain ReferenceType field:\n%s", src)
	}
	if !strings.Contains(src, `ReferenceID string `+"`db:\"reference_id\"`") {
		t.Errorf("missing plain ReferenceID field:\n%s", src)
	}
	// DynamicLink's sibling Selection field must not also generate its
	// own named-string-type version (go-sdk-reference.md §22
	// "DynamicLink" — it names an existing sibling, not a separate
	// allowlist).
	if strings.Contains(src, "AttachmentReferenceType") {
		t.Errorf("sibling Selection field should not generate a separate named type:\n%s", src)
	}
}

// TestRenderModelFile_DynamicLinkPrimaryKeyIsNonPointer pins a real
// inconsistency a code review caught: DynamicLink's sibling and self
// fields computed required from IsRequired alone, unlike every other
// field kind (Selection, Many2One's FK, the default scalar case), which
// all also treat IsPrimaryKey as required.
func TestRenderModelFile_DynamicLinkPrimaryKeyIsNonPointer(t *testing.T) {
	m := model.Define("widgets.link").
		Field("reference_type", model.Selection("sales.order", "contacts.contact").PrimaryKey()).
		Field("reference_id", model.DynamicLink("reference_type").PrimaryKey())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `ReferenceType string `+"`db:\"reference_type\"`") {
		t.Errorf("PK sibling field should be non-pointer:\n%s", src)
	}
	if !strings.Contains(src, `ReferenceID string `+"`db:\"reference_id\"`") {
		t.Errorf("PK DynamicLink field should be non-pointer:\n%s", src)
	}
}

// TestRenderModelFile_TwoDynamicLinkFieldsSharingOneSibling_NoDuplicateField
// pins a real bug a code review caught: two DynamicLink fields (a
// polymorphic link's two ends) naming the same sibling Selection field
// used to emit that sibling's struct field twice — a duplicate field
// name go/format.Source doesn't catch (it only parses/formats, it
// doesn't type-check), so it only ever surfaced as a `go build` failure
// on the generated file.
func TestRenderModelFile_TwoDynamicLinkFieldsSharingOneSibling_NoDuplicateField(t *testing.T) {
	m := model.Define("widgets.link").
		Field("reference_type", model.Selection("widgets.widget", "widgets.gadget").Required()).
		Field("source_id", model.DynamicLink("reference_type").Required()).
		Field("target_id", model.DynamicLink("reference_type").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if n := strings.Count(src, "ReferenceType string"); n != 1 {
		t.Errorf("ReferenceType field emitted %d times, want exactly 1:\n%s", n, src)
	}
	if !strings.Contains(src, `SourceID string `+"`db:\"source_id\"`") {
		t.Errorf("missing SourceID field:\n%s", src)
	}
	if !strings.Contains(src, `TargetID string `+"`db:\"target_id\"`") {
		t.Errorf("missing TargetID field:\n%s", src)
	}
}

// TestRenderModelFile_Many2OneFieldNotEndingInID_Errors pins a real bug:
// a Many2One field name not ending in "_id" made
// strings.TrimSuffix(f.Name, "_id") a silent no-op, so the generated
// orm.Ref[T] expansion field got the exact same Go name as the FK
// field itself — a duplicate struct field, same failure mode as the
// DynamicLink case above.
func TestRenderModelFile_Many2OneFieldNotEndingInID_Errors(t *testing.T) {
	m := model.Define("hr.employee").
		Field("manager", model.Many2One("hr.employee").Required())

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for a Many2One field not ending in \"_id\"")
	}
}

// TestRenderModelFile_Many2OneExpansionCollidesWithSiblingField_Errors
// (goerp#970) pins a real bug: renderModelFile guarded the ResourceName()
// collision and the Many2One "_id"-suffix requirement, but not two
// *fields* on one model whose generated Go names collide.
// go/format.Source only parses and formats — it doesn't type-check — so
// a struct with two fields both named Manager (a manager_id Many2One's
// stripped expansion name landing on an unrelated sibling manager
// field) used to pass straight through as gofmt-clean, non-compiling
// output.
func TestRenderModelFile_Many2OneExpansionCollidesWithSiblingField_Errors(t *testing.T) {
	m := model.Define("hr.employee").
		Field("manager_id", model.Many2One("hr.employee")).
		Field("manager", model.Text())

	_, _, err := renderModelFile(m, nil, testGenContext())
	if err == nil {
		t.Fatal("expected an error for manager_id's Many2One expansion colliding with the sibling manager field")
	}
	if !strings.Contains(err.Error(), "manager_id") || !strings.Contains(err.Error(), `"manager"`) || !strings.Contains(err.Error(), "Manager") {
		t.Errorf("error = %q, want it to name both manager_id and manager and the colliding Go name Manager", err)
	}
}

// TestRenderModelFile_FieldNamesCollidingOnPascalCase_Errors (goerp#970)
// covers the same guard's other trigger: two field names that are
// spelled differently but PascalCase to the same Go identifier, not
// just the Many2One-expansion-specific case above.
func TestRenderModelFile_FieldNamesCollidingOnPascalCase_Errors(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("display_name", model.Text()).
		Field("display-name", model.Text())

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for two field names that PascalCase to the same Go identifier")
	}
}

// TestRenderModelFile_SelectionValueWithNonIdentifierChars pins a real
// bug: pascalCase used to split only on "_", so a Selection/Enum value
// spelled with a hyphen or space (e.g. "in-progress" — nothing in the
// schema DSL rejects that spelling) survived untouched into a generated
// constant name, producing Go source go/format.Source can't parse.
func TestRenderModelFile_SelectionValueWithNonIdentifierChars(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("state", model.Selection("in-progress", "needs review").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `GadgetStateInProgress GadgetState = "in-progress"`) {
		t.Errorf("missing GadgetStateInProgress constant:\n%s", src)
	}
	if !strings.Contains(src, `GadgetStateNeedsReview GadgetState = "needs review"`) {
		t.Errorf("missing GadgetStateNeedsReview constant:\n%s", src)
	}
}

// TestRenderModelFile_EmptyResourceName_Errors pins a real regression: a
// deleted placeholder helper used to guard an empty resource name and
// fall back to a literal "Model" type name; the replacement pascalCase
// has no such guard, and an empty struct name renders as `type  struct`
// — a confusing go/format.Source parse error instead of a clear one
// naming the actual model.
func TestRenderModelFile_EmptyResourceName_Errors(t *testing.T) {
	m := model.Define("")

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for a model with no usable resource name")
	}
}

func TestRenderModelFile_One2ManyIsSkipped(t *testing.T) {
	m := model.Define("contacts.contact").
		Field("address_ids", model.One2Many("contacts.address", "contact_id"))

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if strings.Contains(src, "AddressIds") || strings.Contains(src, "AddressIDs") {
		t.Errorf("One2Many field should be skipped entirely:\n%s", src)
	}
}

func TestRenderModelFile_UnsupportedFieldKind_Errors(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("counter", model.Sequence("{year}").Required())

	// Sequence is supported (string) — this test instead pins that an
	// actually-unrecognized FieldKind value surfaces a clear error
	// rather than silently emitting a broken field, by forging one
	// beyond the declared enum's range.
	m.Fields[0].Def.Kind = model.FieldKind(9999)

	if _, _, err := renderModelFile(m, nil, testGenContext()); err == nil {
		t.Fatal("expected an error for an unsupported field kind")
	}
}

// TestRenderModelFile_GeneratesResourceNameMethod pins goerp#977's own
// AC: every generated struct implements orm.Model via ResourceName().
func TestRenderModelFile_GeneratesResourceNameMethod(t *testing.T) {
	m := model.Define("widgets.widget", model.Table("widgets")).
		WithStandardFields()

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `func (Widget) ResourceName() string { return "widgets.widget" }`) {
		t.Errorf("missing ResourceName() method:\n%s", src)
	}
}

// TestRenderModelFile_FieldDescriptorsPickWrapperPerKind pins goerp#977's
// kind-to-descriptor table (go-sdk-reference.md §22/§26): each base kind
// gets the wrapper type carrying its own extra operators, and
// <Struct>AllFields lists every one of them in declaration order.
func TestRenderModelFile_FieldDescriptorsPickWrapperPerKind(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("name", model.Text().Required()).
		Field("code", model.UUID().Required()).
		Field("quantity", model.Integer().Required()).
		Field("weight", model.Float().Required()).
		Field("is_active", model.Boolean().Required()).
		Field("opened_at", model.TimestampTZ().Required()).
		Field("attachment", model.Bytea()).
		Field("price", model.Decimal(10, 2).Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	for _, want := range []string{
		"Name orm.StringField[Widget]",
		"Code orm.Field[Widget, string]",
		"Quantity orm.OrderedField[Widget, int32]",
		"Weight orm.OrderedField[Widget, float64]",
		"IsActive orm.Field[Widget, bool]",
		"OpenedAt orm.TimeField[Widget]",
		"Attachment orm.BytesField[Widget]",
		// Decimal is the one kind whose struct/wire Go type (string) and
		// descriptor wrapper (OrderedField, for Gt/Lt/Between) diverge
		// from every other string-typed kind (Char/Text/UUID/Sequence).
		"Price orm.OrderedField[Widget, string]",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("WidgetFields missing %q:\n%s", want, src)
		}
	}

	if !strings.Contains(src, "var WidgetAllFields = []orm.AnyField[Widget]{") {
		t.Errorf("missing WidgetAllFields slice:\n%s", src)
	}
	for _, want := range []string{
		"WidgetFields.Name,", "WidgetFields.Code,", "WidgetFields.Quantity,",
		"WidgetFields.Weight,", "WidgetFields.IsActive,", "WidgetFields.OpenedAt,",
		"WidgetFields.Attachment,", "WidgetFields.Price,",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("WidgetAllFields missing entry %q:\n%s", want, src)
		}
	}
}

// TestRenderModelFile_ScanRequiredField pins Scan's required-field
// shape: an absent/NULL value is left unscanned rather than erroring —
// the field simply keeps its zero value, matching a query that didn't
// select it — but a present, type-mismatched value still produces
// *orm.DecodeError. Uses BigInt (int64), the one numeric kind whose
// declared Go type already matches what it decodes as raw — see
// TestRenderModelFile_ScanIntegerFieldNarrowsFromInt64 for the kind that
// doesn't.
func TestRenderModelFile_ScanRequiredField(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("quantity", model.BigInt().Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `if v, ok := row["quantity"]; ok {`) {
		t.Errorf("required field's Scan block should not guard on v != nil:\n%s", src)
	}
	if !strings.Contains(src, `val, ok := v.(int64)`) {
		t.Errorf("missing int64 type assertion:\n%s", src)
	}
	if !strings.Contains(src, `return orm.NewDecodeError("Widget", "Quantity", "int64", v)`) {
		t.Errorf("missing DecodeError construction:\n%s", src)
	}
	if !strings.Contains(src, "x.Quantity = val") {
		t.Errorf("missing field assignment:\n%s", src)
	}
}

// TestRenderModelFile_ScanIntegerFieldNarrowsFromInt64 pins a real bug a
// code review caught: msgpack's own int wire format doesn't preserve the
// host's original int32 width, only the value's magnitude, so a Postgres
// INTEGER column decodes into the guest as int64, not int32 — confirmed
// via a real round trip (goerp#977). Scan must assert against int64 and
// narrow, not assert directly against the struct field's own int32 type
// (which fails on every real record).
func TestRenderModelFile_ScanIntegerFieldNarrowsFromInt64(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("quantity", model.Integer().Required()).
		Field("optional_quantity", model.Integer())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "Quantity int32 ") {
		t.Errorf("struct field should stay int32:\n%s", src)
	}
	if !strings.Contains(src, `val, ok := v.(int64)`) {
		t.Errorf("Scan should assert against int64, not int32:\n%s", src)
	}
	if !strings.Contains(src, `return orm.NewDecodeError("Widget", "Quantity", "int32", v)`) {
		t.Errorf("DecodeError should still name the struct field's own int32 type:\n%s", src)
	}
	if !strings.Contains(src, "x.Quantity = int32(val)") {
		t.Errorf("missing narrowing conversion for the required field:\n%s", src)
	}
	if !strings.Contains(src, "converted := int32(val)") || !strings.Contains(src, "x.OptionalQuantity = &converted") {
		t.Errorf("missing narrowing conversion for the optional field:\n%s", src)
	}
}

// TestRenderModelFile_ScanOptionalField pins Scan's optional-field
// shape: guarded on "ok && v != nil" and assigned via &val, matching the
// struct field's own pointer type.
func TestRenderModelFile_ScanOptionalField(t *testing.T) {
	m := model.Define("widgets.widget").
		Field("nickname", model.Text())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `if v, ok := row["nickname"]; ok && v != nil {`) {
		t.Errorf("optional field's Scan block should guard on v != nil:\n%s", src)
	}
	if !strings.Contains(src, `return orm.NewDecodeError("Widget", "Nickname", "*string", v)`) {
		t.Errorf("optional field's DecodeError should name the pointer type:\n%s", src)
	}
	if !strings.Contains(src, "x.Nickname = &val") {
		t.Errorf("missing pointer field assignment:\n%s", src)
	}
}

// TestRenderModelFile_ScanNamedTypeField pins Scan's Selection/Enum
// shape: the raw value asserts as a plain string, then converts to the
// field's own named type.
func TestRenderModelFile_ScanNamedTypeField(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("state", model.Selection("draft", "done").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `s, ok := v.(string)`) {
		t.Errorf("named-type field should assert against string:\n%s", src)
	}
	if !strings.Contains(src, "x.State = GadgetState(s)") {
		t.Errorf("missing named-type conversion:\n%s", src)
	}
}

// TestRenderModelFile_ScanRelationExpansion pins Scan's Many2One
// expansion shape: always guarded on v != nil regardless of the FK's own
// required-ness, decoding the nested {id, display_name} object into an
// orm.Ref[T] — and that the expansion gets no field descriptor (it's not
// Condition-bearing).
func TestRenderModelFile_ScanRelationExpansion(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("customer_id", model.Many2One("contacts.contact").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, `if v, ok := row["customer"]; ok && v != nil {`) {
		t.Errorf("missing relation expansion Scan guard:\n%s", src)
	}
	if !strings.Contains(src, "nested, ok := v.(map[string]any)") {
		t.Errorf("missing nested map assertion:\n%s", src)
	}
	if !strings.Contains(src, `ref.ID = id`) || !strings.Contains(src, "ref.DisplayName = dn") {
		t.Errorf("missing RelationRef field extraction:\n%s", src)
	}
	if !strings.Contains(src, "x.Customer = orm.Ref[ContactsContactRef]{RelationRef: &ref}") {
		t.Errorf("missing expansion field assignment:\n%s", src)
	}
	if strings.Contains(src, "GadgetFields.Customer,") {
		t.Errorf("Many2One expansion should not get an AllFields entry:\n%s", src)
	}
	if strings.Contains(src, "Customer orm.Field[") {
		t.Errorf("Many2One expansion should not get a field descriptor:\n%s", src)
	}
}

// TestRenderModelFile_ValuesBuilder_EmitsSetXPerWritableField pins
// issue #978's own scope example — a SetX method per writable field,
// each going through orm.Set (or orm.SetBytes for BytesField), and
// StringField/OrderedField/TimeField's own SetX addressing the embedded
// Field via ".Field", since the wrapper type itself doesn't satisfy
// Set's Field[T, TValue] parameter.
func TestRenderModelFile_ValuesBuilder_EmitsSetXPerWritableField(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("name", model.Text().Required()).
		Field("code", model.UUID().Required()).
		Field("quantity", model.Integer().Required()).
		Field("opened_at", model.TimestampTZ().Required()).
		Field("attachment", model.Bytea()).
		Field("state", model.Selection("draft", "done").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "type GadgetValues struct {") || !strings.Contains(src, "orm.Values[Gadget]") {
		t.Errorf("missing GadgetValues struct embedding orm.Values[Gadget]:\n%s", src)
	}
	if !strings.Contains(src, "func NewGadgetValues() *GadgetValues {") ||
		!strings.Contains(src, "return &GadgetValues{Values: *orm.NewValues[Gadget]()}") {
		t.Errorf("missing NewGadgetValues constructor:\n%s", src)
	}

	for _, want := range []string{
		// StringField — .Field required.
		"func (v *GadgetValues) SetName(x string) *GadgetValues {",
		"orm.Set(&v.Values, GadgetFields.Name.Field, x)",
		// plain Field — no .Field.
		"func (v *GadgetValues) SetCode(x string) *GadgetValues {",
		"orm.Set(&v.Values, GadgetFields.Code, x)",
		// OrderedField — .Field required.
		"func (v *GadgetValues) SetQuantity(x int32) *GadgetValues {",
		"orm.Set(&v.Values, GadgetFields.Quantity.Field, x)",
		// TimeField — .Field required.
		"func (v *GadgetValues) SetOpenedAt(x time.Time) *GadgetValues {",
		"orm.Set(&v.Values, GadgetFields.OpenedAt.Field, x)",
		// BytesField — orm.SetBytes, no .Field.
		"func (v *GadgetValues) SetAttachment(x []byte) *GadgetValues {",
		"orm.SetBytes(&v.Values, GadgetFields.Attachment, x)",
		// Selection's named type — plain Field, no .Field.
		"func (v *GadgetValues) SetState(x GadgetState) *GadgetValues {",
		"orm.Set(&v.Values, GadgetFields.State, x)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("output missing %q:\n%s", want, src)
		}
	}
}

// TestRenderModelFile_ValuesBuilder_SkipsReadonlyAndComputedFields pins
// the other half of #978's AC: a Readonly or Computed field gets no
// SetX — the compile-time counterpart to host.orm's own runtime
// orm.field_not_writable rejection.
func TestRenderModelFile_ValuesBuilder_SkipsReadonlyAndComputedFields(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("name", model.Text().Required()).
		Field("locked_note", model.Text().Readonly()).
		Field("total", model.Float().Computed("compute_total").Store(true))

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "func (v *GadgetValues) SetName(x string) *GadgetValues {") {
		t.Errorf("writable field Name should still get a SetX method:\n%s", src)
	}
	if strings.Contains(src, "SetLockedNote") {
		t.Errorf("Readonly field should not get a SetX method:\n%s", src)
	}
	if strings.Contains(src, "SetTotal") {
		t.Errorf("Computed field should not get a SetX method:\n%s", src)
	}
}

// TestRenderModelFile_ValuesBuilder_Many2OneExpansionHasNoSetter pins
// that only the FK ID field is writable — the orm.Ref[T]
// expansion isn't a real column and gets no field descriptor (already
// pinned by TestRenderModelFile_ScanRelationExpansion) or SetX.
func TestRenderModelFile_ValuesBuilder_Many2OneExpansionHasNoSetter(t *testing.T) {
	m := model.Define("widgets.gadget").
		Field("customer_id", model.Many2One("contacts.contact").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if !strings.Contains(src, "func (v *GadgetValues) SetCustomerID(x string) *GadgetValues {") {
		t.Errorf("missing SetCustomerID for the Many2One FK field:\n%s", src)
	}
	if strings.Contains(src, "SetCustomer(") {
		t.Errorf("Many2One expansion should not get a SetX method:\n%s", src)
	}
}

// TestRenderModelFile_ValuesBuilder_DynamicLinkFieldsAreWritable pins
// that both a DynamicLink field and its sibling Selection field, sharing
// one struct field, still each get exactly one SetX method — not
// duplicated the way TestRenderModelFile_TwoDynamicLinkFieldsSharingOneSibling_NoDuplicateField
// pins for the struct field itself.
func TestRenderModelFile_ValuesBuilder_DynamicLinkFieldsAreWritable(t *testing.T) {
	m := model.Define("widgets.link").
		Field("reference_type", model.Selection("sales.order", "contacts.contact").Required()).
		Field("source_id", model.DynamicLink("reference_type").Required()).
		Field("target_id", model.DynamicLink("reference_type").Required())

	out, _, err := renderModelFile(m, nil, testGenContext())
	if err != nil {
		t.Fatalf("renderModelFile: %v", err)
	}
	src := normalizeSpaces(string(out))

	if n := strings.Count(src, "func (v *LinkValues) SetReferenceType("); n != 1 {
		t.Errorf("SetReferenceType emitted %d times, want exactly 1:\n%s", n, src)
	}
	if !strings.Contains(src, "func (v *LinkValues) SetSourceID(x string) *LinkValues {") {
		t.Errorf("missing SetSourceID:\n%s", src)
	}
	if !strings.Contains(src, "func (v *LinkValues) SetTargetID(x string) *LinkValues {") {
		t.Errorf("missing SetTargetID:\n%s", src)
	}
}
