// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Contact corresponds to model "contacts.contact".
type Contact struct {
	ID          string           `db:"id"`
	TenantID    string           `db:"tenant_id"`
	CreatedAt   time.Time        `db:"created_at"`
	UpdatedAt   time.Time        `db:"updated_at"`
	DeletedAt   *time.Time       `db:"deleted_at"`
	CreatedBy   *string          `db:"created_by"`
	Etag        string           `db:"etag"`
	Type        ContactType      `db:"type"`
	Name        string           `db:"name"`
	DisplayName *string          `db:"display_name"`
	CompanyID   *string          `db:"company_id"`
	Company     orm.Ref[Contact] `db:"company"`
	Phone       *string          `db:"phone"`
	Mobile      *string          `db:"mobile"`
	Email       *string          `db:"email"`
	Street      *string          `db:"street"`
	City        *string          `db:"city"`
	CountryCode *string          `db:"country_code"`
	Tin         *string          `db:"tin"`
	Website     *string          `db:"website"`
	IsCustomer  bool             `db:"is_customer"`
	IsSupplier  bool             `db:"is_supplier"`
	IsActive    bool             `db:"is_active"`
	Notes       *string          `db:"notes"`
}

func (Contact) ResourceName() string { return "contacts.contact" }

// ContactFields is one orm field descriptor per Condition-bearing column.
var ContactFields = struct {
	ID          orm.Field[Contact, string]
	TenantID    orm.Field[Contact, string]
	CreatedAt   orm.TimeField[Contact]
	UpdatedAt   orm.TimeField[Contact]
	DeletedAt   orm.TimeField[Contact]
	CreatedBy   orm.Field[Contact, string]
	Etag        orm.StringField[Contact]
	Type        orm.Field[Contact, ContactType]
	Name        orm.StringField[Contact]
	DisplayName orm.StringField[Contact]
	CompanyID   orm.Field[Contact, string]
	Phone       orm.StringField[Contact]
	Mobile      orm.StringField[Contact]
	Email       orm.StringField[Contact]
	Street      orm.StringField[Contact]
	City        orm.StringField[Contact]
	CountryCode orm.StringField[Contact]
	Tin         orm.StringField[Contact]
	Website     orm.StringField[Contact]
	IsCustomer  orm.Field[Contact, bool]
	IsSupplier  orm.Field[Contact, bool]
	IsActive    orm.Field[Contact, bool]
	Notes       orm.StringField[Contact]
}{
	ID:          orm.NewField[Contact, string]("id"),
	TenantID:    orm.NewField[Contact, string]("tenant_id"),
	CreatedAt:   orm.NewTimeField[Contact]("created_at"),
	UpdatedAt:   orm.NewTimeField[Contact]("updated_at"),
	DeletedAt:   orm.NewTimeField[Contact]("deleted_at"),
	CreatedBy:   orm.NewField[Contact, string]("created_by"),
	Etag:        orm.NewStringField[Contact]("etag"),
	Type:        orm.NewField[Contact, ContactType]("type"),
	Name:        orm.NewStringField[Contact]("name"),
	DisplayName: orm.NewStringField[Contact]("display_name"),
	CompanyID:   orm.NewField[Contact, string]("company_id"),
	Phone:       orm.NewStringField[Contact]("phone"),
	Mobile:      orm.NewStringField[Contact]("mobile"),
	Email:       orm.NewStringField[Contact]("email"),
	Street:      orm.NewStringField[Contact]("street"),
	City:        orm.NewStringField[Contact]("city"),
	CountryCode: orm.NewStringField[Contact]("country_code"),
	Tin:         orm.NewStringField[Contact]("tin"),
	Website:     orm.NewStringField[Contact]("website"),
	IsCustomer:  orm.NewField[Contact, bool]("is_customer"),
	IsSupplier:  orm.NewField[Contact, bool]("is_supplier"),
	IsActive:    orm.NewField[Contact, bool]("is_active"),
	Notes:       orm.NewStringField[Contact]("notes"),
}

// ContactAllFields is Query[Contact]'s default Select() list.
var ContactAllFields = []orm.AnyField[Contact]{
	ContactFields.ID,
	ContactFields.TenantID,
	ContactFields.CreatedAt,
	ContactFields.UpdatedAt,
	ContactFields.DeletedAt,
	ContactFields.CreatedBy,
	ContactFields.Etag,
	ContactFields.Type,
	ContactFields.Name,
	ContactFields.DisplayName,
	ContactFields.CompanyID,
	ContactFields.Phone,
	ContactFields.Mobile,
	ContactFields.Email,
	ContactFields.Street,
	ContactFields.City,
	ContactFields.CountryCode,
	ContactFields.Tin,
	ContactFields.Website,
	ContactFields.IsCustomer,
	ContactFields.IsSupplier,
	ContactFields.IsActive,
	ContactFields.Notes,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Contact) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Contact", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Contact", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Contact", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["type"]; ok {
		s, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Type", "ContactType", v)
		}
		x.Type = ContactType(s)
	}
	if v, ok := row["name"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Name", "string", v)
		}
		x.Name = val
	}
	if v, ok := row["display_name"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "DisplayName", "*string", v)
		}
		x.DisplayName = &val
	}
	if v, ok := row["company_id"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "CompanyID", "*string", v)
		}
		x.CompanyID = &val
	}
	if v, ok := row["company"]; ok && v != nil {
		nested, ok := v.(map[string]any)
		if !ok {
			return orm.NewDecodeError("Contact", "Company", "orm.Ref[Contact]", v)
		}
		ref := orm.RelationRef{}
		if id, ok := nested["id"].(string); ok {
			ref.ID = id
		}
		if dn, ok := nested["display_name"].(string); ok {
			ref.DisplayName = dn
		}
		x.Company = orm.Ref[Contact]{RelationRef: &ref}
	}
	if v, ok := row["phone"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Phone", "*string", v)
		}
		x.Phone = &val
	}
	if v, ok := row["mobile"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Mobile", "*string", v)
		}
		x.Mobile = &val
	}
	if v, ok := row["email"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Email", "*string", v)
		}
		x.Email = &val
	}
	if v, ok := row["street"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Street", "*string", v)
		}
		x.Street = &val
	}
	if v, ok := row["city"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "City", "*string", v)
		}
		x.City = &val
	}
	if v, ok := row["country_code"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "CountryCode", "*string", v)
		}
		x.CountryCode = &val
	}
	if v, ok := row["tin"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Tin", "*string", v)
		}
		x.Tin = &val
	}
	if v, ok := row["website"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Website", "*string", v)
		}
		x.Website = &val
	}
	if v, ok := row["is_customer"]; ok {
		val, ok := v.(bool)
		if !ok {
			return orm.NewDecodeError("Contact", "IsCustomer", "bool", v)
		}
		x.IsCustomer = val
	}
	if v, ok := row["is_supplier"]; ok {
		val, ok := v.(bool)
		if !ok {
			return orm.NewDecodeError("Contact", "IsSupplier", "bool", v)
		}
		x.IsSupplier = val
	}
	if v, ok := row["is_active"]; ok {
		val, ok := v.(bool)
		if !ok {
			return orm.NewDecodeError("Contact", "IsActive", "bool", v)
		}
		x.IsActive = val
	}
	if v, ok := row["notes"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Contact", "Notes", "*string", v)
		}
		x.Notes = &val
	}
	return nil
}

// ContactValues is a typed builder for Contact's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type ContactValues struct {
	orm.Values[Contact]
}

func NewContactValues() *ContactValues {
	return &ContactValues{Values: *orm.NewValues[Contact]()}
}

func (v *ContactValues) SetType(x ContactType) *ContactValues {
	v.Values.Set(ContactFields.Type, x)
	return v
}

func (v *ContactValues) SetName(x string) *ContactValues {
	v.Values.Set(ContactFields.Name.Field, x)
	return v
}

func (v *ContactValues) SetCompanyID(x string) *ContactValues {
	v.Values.Set(ContactFields.CompanyID, x)
	return v
}

func (v *ContactValues) SetPhone(x string) *ContactValues {
	v.Values.Set(ContactFields.Phone.Field, x)
	return v
}

func (v *ContactValues) SetMobile(x string) *ContactValues {
	v.Values.Set(ContactFields.Mobile.Field, x)
	return v
}

func (v *ContactValues) SetEmail(x string) *ContactValues {
	v.Values.Set(ContactFields.Email.Field, x)
	return v
}

func (v *ContactValues) SetStreet(x string) *ContactValues {
	v.Values.Set(ContactFields.Street.Field, x)
	return v
}

func (v *ContactValues) SetCity(x string) *ContactValues {
	v.Values.Set(ContactFields.City.Field, x)
	return v
}

func (v *ContactValues) SetCountryCode(x string) *ContactValues {
	v.Values.Set(ContactFields.CountryCode.Field, x)
	return v
}

func (v *ContactValues) SetTin(x string) *ContactValues {
	v.Values.Set(ContactFields.Tin.Field, x)
	return v
}

func (v *ContactValues) SetWebsite(x string) *ContactValues {
	v.Values.Set(ContactFields.Website.Field, x)
	return v
}

func (v *ContactValues) SetIsCustomer(x bool) *ContactValues {
	v.Values.Set(ContactFields.IsCustomer, x)
	return v
}

func (v *ContactValues) SetIsSupplier(x bool) *ContactValues {
	v.Values.Set(ContactFields.IsSupplier, x)
	return v
}

func (v *ContactValues) SetIsActive(x bool) *ContactValues {
	v.Values.Set(ContactFields.IsActive, x)
	return v
}

func (v *ContactValues) SetNotes(x string) *ContactValues {
	v.Values.Set(ContactFields.Notes.Field, x)
	return v
}

// ValueFields maps every column of Contact to the decoder of its JSON form; a nil
// entry is a read-only field. orm.Values[Contact] decodes request bodies with it.
func (Contact) ValueFields() map[string]orm.ValueDecoder {
	return map[string]orm.ValueDecoder{
		"id":           nil,
		"tenant_id":    nil,
		"created_at":   nil,
		"updated_at":   nil,
		"deleted_at":   nil,
		"created_by":   nil,
		"etag":         nil,
		"type":         orm.DecodeValue[ContactType],
		"name":         orm.DecodeValue[string],
		"display_name": nil,
		"company_id":   orm.DecodeValue[string],
		"phone":        orm.DecodeValue[string],
		"mobile":       orm.DecodeValue[string],
		"email":        orm.DecodeValue[string],
		"street":       orm.DecodeValue[string],
		"city":         orm.DecodeValue[string],
		"country_code": orm.DecodeValue[string],
		"tin":          orm.DecodeValue[string],
		"website":      orm.DecodeValue[string],
		"is_customer":  orm.DecodeValue[bool],
		"is_supplier":  orm.DecodeValue[bool],
		"is_active":    orm.DecodeValue[bool],
		"notes":        orm.DecodeValue[string],
	}
}

// Query returns a fresh Contact query — sugar over orm.From[Contact]().
func (Contact) Query() *orm.Query[Contact] { return orm.From[Contact]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Contact].
func (x Contact) Delete() (orm.ExecResult, error) { return orm.Unlink[Contact](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Contact) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Contact](tx, x.ID) }

type ContactType string

const (
	ContactTypePerson  ContactType = "person"
	ContactTypeCompany ContactType = "company"
)
