// Code generated by goerp module generate. DO NOT EDIT.

package models

import (
	"time"

	"github.com/djangbahevans/goerp/sdk/go/db"
	"github.com/djangbahevans/goerp/sdk/go/orm"
)

// Item corresponds to model "demo.item".
type Item struct {
	ID        string     `db:"id"`
	TenantID  string     `db:"tenant_id"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
	CreatedBy *string    `db:"created_by"`
	Etag      string     `db:"etag"`
	Name      string     `db:"name"`
}

func (Item) ResourceName() string { return "demo.item" }

// ItemFields is one orm field descriptor per Condition-bearing column.
var ItemFields = struct {
	ID        orm.Field[Item, string]
	TenantID  orm.Field[Item, string]
	CreatedAt orm.TimeField[Item]
	UpdatedAt orm.TimeField[Item]
	DeletedAt orm.TimeField[Item]
	CreatedBy orm.Field[Item, string]
	Etag      orm.StringField[Item]
	Name      orm.StringField[Item]
}{
	ID:        orm.NewField[Item, string]("id"),
	TenantID:  orm.NewField[Item, string]("tenant_id"),
	CreatedAt: orm.NewTimeField[Item]("created_at"),
	UpdatedAt: orm.NewTimeField[Item]("updated_at"),
	DeletedAt: orm.NewTimeField[Item]("deleted_at"),
	CreatedBy: orm.NewField[Item, string]("created_by"),
	Etag:      orm.NewStringField[Item]("etag"),
	Name:      orm.NewStringField[Item]("name"),
}

// ItemAllFields is Query[Item]'s default Select() list.
var ItemAllFields = []orm.AnyField[Item]{
	ItemFields.ID,
	ItemFields.TenantID,
	ItemFields.CreatedAt,
	ItemFields.UpdatedAt,
	ItemFields.DeletedAt,
	ItemFields.CreatedBy,
	ItemFields.Etag,
	ItemFields.Name,
}

// Scan populates x from row, a single record as host.orm returns it.
func (x *Item) Scan(row map[string]any) error {
	if v, ok := row["id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Item", "ID", "string", v)
		}
		x.ID = val
	}
	if v, ok := row["tenant_id"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Item", "TenantID", "string", v)
		}
		x.TenantID = val
	}
	if v, ok := row["created_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Item", "CreatedAt", "time.Time", v)
		}
		x.CreatedAt = val
	}
	if v, ok := row["updated_at"]; ok {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Item", "UpdatedAt", "time.Time", v)
		}
		x.UpdatedAt = val
	}
	if v, ok := row["deleted_at"]; ok && v != nil {
		val, ok := v.(time.Time)
		if !ok {
			return orm.NewDecodeError("Item", "DeletedAt", "*time.Time", v)
		}
		x.DeletedAt = &val
	}
	if v, ok := row["created_by"]; ok && v != nil {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Item", "CreatedBy", "*string", v)
		}
		x.CreatedBy = &val
	}
	if v, ok := row["etag"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Item", "Etag", "string", v)
		}
		x.Etag = val
	}
	if v, ok := row["name"]; ok {
		val, ok := v.(string)
		if !ok {
			return orm.NewDecodeError("Item", "Name", "string", v)
		}
		x.Name = val
	}
	return nil
}

// ItemValues is a typed builder for Item's writable fields — one SetX
// method per field goerp module generate found writable (not Readonly,
// not Computed). The same builder serves both Create and Write: Create
// sends every key present, Write sends only the keys present.
type ItemValues struct {
	orm.Values[Item]
}

func NewItemValues() *ItemValues {
	return &ItemValues{Values: *orm.NewValues[Item]()}
}

func (v *ItemValues) SetName(x string) *ItemValues {
	v.Values.Set(ItemFields.Name.Field, x)
	return v
}

// ValueFields maps every column of Item to the decoder of its JSON form; a nil
// entry is a read-only field. orm.Values[Item] decodes request bodies with it.
func (Item) ValueFields() map[string]orm.ValueDecoder {
	return map[string]orm.ValueDecoder{
		"id":         nil,
		"tenant_id":  nil,
		"created_at": nil,
		"updated_at": nil,
		"deleted_at": nil,
		"created_by": nil,
		"etag":       nil,
		"name":       orm.DecodeValue[string],
	}
}

// Query returns a fresh Item query — sugar over orm.From[Item]().
func (Item) Query() *orm.Query[Item] { return orm.From[Item]() }

// Delete deletes x by its primary key — sugar over orm.Unlink[Item].
func (x Item) Delete() (orm.ExecResult, error) { return orm.Unlink[Item](x.ID) }

// DeleteTx is Delete, scoped to tx's own open transaction.
func (x Item) DeleteTx(tx *db.Tx) (orm.ExecResult, error) { return orm.UnlinkTx[Item](tx, x.ID) }
